enigma-dev/enigma-dev

CompilerSource/compiler/components/parse_and_link.cpp
CompilerSource/parser/parser.cpp
CompilerSource/parser/parser_components.cpp
CompilerSource/settings-parse/parse_ide_settings.cpp
CompilerSource/settings.cpp
CompilerSource/settings.h
settings.ey

Adds a setting to ENIGMA settings to disable automatic semicolons during the main parsing phase. This allows the user to build projects faster with strict syntax. This will fall through syntax checking and it will be picked up by MinGW and displayed in LGM's console window, though scope is harder to determine because the user will need to know and make sense of what is written to PREPROCESSOR_ENVIRONMENT_EDITABLE in order to fix syntax errors. This is considered an advanced setting. This is a temporary way of addressing #916 as EDL may have its own syntax for initialization lists which may or may not be compatible with C++'s, though GM: Studio's might possibly be. Additionally because GM users like to omit semicolons in statements, some games may fail to build if this setting is disabled. …

Compiler Settings

---

ENIGMAsystem/SHELL/Platforms/Cocoa/CocoaWindow.cpp
ENIGMAsystem/SHELL/Platforms/Cocoa/WindowFunctions.m

Now you (on OS-X) can copy and paste stuff between ENIGMA apps and other apps with ease! Strings larger than 1MB will be safely truncated.

Implements the clipboard functions on OS-X.

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9surface.cpp

@TheExDeus forgot to update the surface_create signature causing Project
Mario not to build.

Fix Direct3D9

---

ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp

The directory chooser callback should have been INT all along and not INT_PTR like the other callsbacks.
The directory chooser signature should follow this:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb762598%28v=vs.85%29.aspx
The other dialogs we show with DialogBox should follow the DialogProc signature:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms645469%28v=vs.85%29.aspx
I tested this change with both MinGW 32 and 64 and it works fine, and now makes the widgets partially build on MinGW 64 with less errors.

Windows Widgets for MinGW64

---

ENIGMAsystem/SHELL/Widget_Systems/Win32/widgets.cpp

Fixes remaining warnings and errors for building the Win32 widgets with MinGW64. Tested for both MinGW32 and 64 and all warnings and errors have been resolved.
Cast to ptrdiff_t for warnings was @JoshDreamlands idea.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms632680%28v=vs.85%29.aspx
He also told me to always use long pointer for 32bit and 64bit for setID/getID

Win32 Widget Errors and Warnings MinGW64

---

Compilers/Linux/clang.ey
Compilers/Linux/clang32.ey

This switches clang to C++11, which is in line with GCC. In order to work around some other bugs, I have also switched libstdc++ to libc++ (the LLVM c++ standard library) for clang.

Use C++11 and libc++ for Clang/Clang32.

---

ENIGMAsystem/SHELL/Platforms/Cocoa/CocoaFunctions.cpp

Due to an oversight, keyboard_key and keyboard_lastkey were never hooked up on OS-X. This fixes that.

Fixes keyboard_lastkey and keyboard_key for OS-X

---

ENIGMAsystem/SHELL/Audio_Systems/General/ASadvanced.h
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALadvanced.cpp

audio_master_gain() had the unused argument time, which was not present in any documentation of the function, so I removed it.

Fixed audio_master_gain()

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSstdraw.cpp

draw_circle() had an if statement in which some identical code would be executed either way, as well as a variable that was storing a value that would only be used once every iteration and would have to be recalculated for every iteration anyway.

Improved efficiency of draw_circle()

---

CompilerSource/compiler/compile.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSbackground.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSbackground.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSfont.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSsurface.cpp

Fixes #967 and #956 .
Fyi I had to `#include "Graphics_Systems/General/GScolors.h"` so I could use draw_get_alpha() in GSbackground.

Fixed alpha issues

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11surface.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9surface.cpp

This fixes Direct3D9 and Direct3D11. @TheExDeus added a "bool depthbuffer" parameter to the general surface functions header but never updated the Direct3D backends. So they would not build for any game that uses surfaces, which was stopping Project Mario from building.
Also converts tabs to two spaces, and removes excess whitespace in the files.

Fixes Direct3D

---

CompilerSource/compiler/components/write_object_data.cpp

Removes excess whitespace and uses string.empty() to check when a string is empty instead of comparing it to a 0 length string literal like the rest of the compiler source code does.
Also fixes #981 as I described in https://github.com/enigma-dev/enigma-dev/issues/870#issuecomment-226436467
WIth this fix the platforming example that is at the top of the EDC builds and runs again just fine as it did before. Project Mario and other inheritance examples I have continue to function normally.

Cleanup write_object_data.cpp

---

ENIGMAsystem/SHELL/Universal_System/Extensions/Alarms/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/Asynchronous/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/BasicGUI/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/Box2D/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/BulletDynamics/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/DateTime/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/DirectShow/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/GM5Compat/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/GME/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/IniFilesystem/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/Json/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/MCI/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/Matrix/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/MotionPlanning/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/ParticleSystems/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/Paths/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/RegistrySpoof/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/StudioPhysics/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/Timelines/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/WindowsTouch/About.ey
ENIGMAsystem/SHELL/Universal_System/Extensions/XInput/About.ey

There are two changes here. First, "ID" is being changed to "Identifier" for extensions as it is for the major systems so there is consistency. Second, "Name" was intended to be the human readable field as it is used in the major systems, but due to a bug that I just fixed in the plugin (https://github.com/enigma-dev/lgmplugin/commit/ccc750ac54745d05599299549c13a29d91b659d4) "Identifier" was being used instead. So this PR swaps the role of "Identifier" and "Name".
Once this is merged, everybody is going to need the new ENIGMA plugin. Read the topic for more information about this issue.
http://enigma-dev.org/forums/index.php?topic=2718

Correct extension About.ey files

---

ENIGMAsystem/SHELL/Universal_System/estring.cpp
ENIGMAsystem/SHELL/Universal_System/estring.h

This PR fully fixes #955
Fixes the indentation and whitespace around the string functions to improve readability. Also corrects ``string_upper`` and ``string_lower`` to handle zero length strings. They actually were not working before and were missing the last character. After this PR they should work correctly, here is a test:
```gml
show_message(string_lower("")); // should be ""
show_message(string_lower("A")); // should be "a"
show_message(string_lower("AA")); // should be "aa"
show_message(string_upper("")); // should be ""
show_message(string_upper("a")); // should be "A"
show_message(string_upper("aa")); // should be "AA"
```
While I was in here I also fixed the behavior and return type of ``string_pos``
According to the GM 5 manual and the GMS manual as well as ENIGMA's Wiki it …

Cleanup string functions

---

CompilerSource/Makefile

See:
https://github.com/enigma-dev/enigma-dev/pull/929#issuecomment-247857016

Fixes compileEGMf always compiling to 32-bit rather than native.

---

CompilerSource/settings-parse/parse_ide_settings.cpp

Partial fix for #944. Fixes compilation and dynamic linkage under Arch with GCC 6.2.1, but JDI is still crashing later on.

Fix #944 (use of external inline function)

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3shader.cpp

-There was a memory leak in glsl_shader_print_infolog and glsl_program_print_infolog. The malloc's didn't have free's.
A better way to be using a char array or even a presized std::string anyway.

Memory leak fix

---

ENIGMAsystem/SHELL/Universal_System/instance_create.h

Use `instance_destroy(id, call_destroy)` instead, as this handles cleaning up dangling iterators. This function is still a major hack; not sure who wrote it. At least now it won't segfault.
Fixes #1045.

Fix careless unlink call in `instance_change()`

---

ENIGMAsystem/SHELL/Universal_System/Extensions/Box2D/Box2DWorld.h

Despite calling ```b2d_body_delete()``` Box2D objects wouldn't be destroyed, all that would happen would be that the memory for the struct that encapsulates Box2D objects would be freed, which would mean you would end up with ghost bodies in a Box2D world (Box2D bodies not attached to an ENIGMA object).

Fixed Box2D bodies not being destroyed

---

ENIGMAsystem/SHELL/Bridges/General/DX9Context.h
ENIGMAsystem/SHELL/Bridges/Win32-Direct3D9/graphics_bridge.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11model.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11vertex.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9ModelStruct.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9SurfaceStruct.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9model.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9vertex.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSvertex.h

Resolves #1034 but these systems need another look. After merging this I want to move all that model code out into the general system and have it make use of the vertex buffer functions. I am sick of looking at all of the duplicated model handling code, it's very ugly.
1) Fixes my warning about the stride of the last primitive batch, can just check if it's 0 since that is an invalid stride.
2) Fixes various formatting and indentation, such as consistent use of 2 spaces, removing blank lines with whitespace characters, etc.
3) Fixes warning about casting NULL to DWORD, convention is to just set d3dpp.flags to 0 since DWORD is unsigned long.
4) Adds the missing format parameter for d3d_model_primitive_begin which was making all the calls have ambiguous overload.
5) Add empty shells for …

Cleanup and fix Direct3D graphics systems

---

appveyor.yml

1) Adds the plugin method ``log_make_to_console()`` so that the CLI can bypass the file redirect and let GCC output directly with color. This is actually how it should have been originally done and LGM's console should have been just reading from stdout.
2) Regardless, this has made that print-loop in the CLI useless now so I've also removed it and its includes.
3) Additionally, I fixed a bug with ``e_exec()`` not flushing its output.
4) Added a missing line about "Debug" to the information for the ``--mode`` option.
5) Cut the average build time of AppVeyor in half. I did this by not redownloading and reinstalling mingw-w64, git, zlib, and ffi which are already installed on the system. This was just vestigial leftovers from me trying to get GCC 7.2 to avoid that ``alloca(...)`` problem …

Color output + GCC redirect disabling

---

.travis.yml
appveyor.yml

Ok, so basically my caching improvements in #1101 were misguided. The cache is actually best used for dependencies, as AppVeyor and Travis CI both mention in their documentation, not for binary blobs and shared artifacts of the build. Specifically, neither continuous integration service currently has shared caches and uses a unique cache for every job as an expansion of the build matrix and environment. I have found places on GitHub where some of the developers behind these CI services are looking into shared caches though.
What this change does for our AppVeyor builds is designate the initial job for building JDI and the CLI, like it did before. But instead of using the cache it now zips them into an archive and uploads them as an artifact. This results in more predictable and consistent …

AppVeyor artifacts and cache efficiency improvement

---

appveyor.yml

Ok, lots of great improvements here. I've learned so much about PowerShell, CMD, Bash and general shell scripting the past few days. While my last changes to AppVeyor made it more reliable, this now makes it totally correct.
I wanted to address the issue with feature branches that caused 4 builds to run on Josh's PR he created from a branch the other day. All I had to do was whitelist only "master" for Travis CI. I did the same for AppVeyor as well, but I also noticed that its shorter version of the same option was using my commit "Update AppVeyor.yml" instead of my pull request title in its UI, so I tried the Travis CI way with it too. That's why I opened 3 pull requests in total for this, the other two are closed. Regardless, it didn't work, so I changed it back to the shorter version …

Continuous integration fixes for "feature" branches/blobs archive

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.h
ENIGMAsystem/SHELL/Platforms/xlib/XLIBmain.cpp

Fixes #1039  
I decided to have it so url_open() can optionally take the arguments specified for its associated functions, url_open_ext() and url_open_full(), since they extend each other in case some platform can actually implement them.  
Also implemented action_webpage() for Linux while I was at it.

Added url_open() and associated functions

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp

- Before this change, on Windows, there was a 640x480 window, (with a solid-black client area), that would show at immediately after opening your game executable, and it displays however long it takes for the game to initialize everything. I made it so that window stays hidden until everything is initialized, this way there won't be a nasty random 640x480 window at the start of every game.

 This hides the 640x480 black loading window, etc.

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp

I discovered in #1105 that ENIGMA's ``window_default`` was behaving slightly different than GM's. It was not supposed to set the window visible if it wasn't already, which it was, because ShowWindow was called to set the fullscreen state. It was setting it visible regardless of the WS_VISIBLE flag because ShowWindow does not care about that flag. This was inconsistent with how we were handling the other window styles, and also created redundant code.
With these changes, the following will behave exactly as it does in GM8.1, meaning the main window will only be visible for the first message:
```gml
show_message("main window should be visible...");
window_set_visible(false);
show_message("main window should be invisible...");
window_default();
show_message("main window should be visible? in …
```

Fixes window fullscreen behavior

---

CommandLine/emake/OptionsParser.cpp
CompilerSource/makedir.cpp
CompilerSource/settings-parse/parse_ide_settings.cpp
settings.ey

We were using `%PROGRAMDATA%` before which did not exist on Windows XP and created problems for older users trying to install ENIGMA. It used to be called the **`All Users`** folder or something on Windows, but the environment var wasn't mapped. That folder is where Windows applications should store global settings and files that all users can access. That folder is also what the Education versions of GameMaker use to make a global install on shared school computers:
https://help.yoyogames.com/hc/en-us/articles/216755378-GameMaker-Studio-Education-Version
This pull request changes ENIGMA to use `%LOCALAPPDATA%`, just like GameMaker: Studio, which is specific to each user. This is currently what GameMaker: Studio uses by default to write the game with the YYC. This is also more consistent …

Change Default Windows Make Directory For Game

---

appveyor.yml

Our AppVeyor status is now failing from Josh using a feature branch to test/cherrypick fundies PR. This is all we ever use branches for, and building them tends to just waste build cycles. So I have decided we should make a whitelist of branches to build, and, for now, only include master.

Make AppVeyor only build the master branch

---

appveyor.yml

It does this because GTK triggers an update to the font cache, and some other libraries may too. We don't actually need it in order to test anything. Since it holds our build up significantly, we can just disable it with `MSYS2_FC_CACHE_SKIP` to skip it.

Skip AppVeyor Font Cache Update

---

ENIGMAsystem/SHELL/Platforms/xlib/XLIBmain.cpp

This will enable a test harness to properly identify ENIGMA windows to manipulate them and read their attributes.

Set _NET_WM_PID on X11 windows.

---

appveyor.yml

The problem was that the REST API basically returns you the jobs of the current build, which happens to be the latest, not the one it's actually building. So we just look up the specific build using the build version environment variable. This should fix multiple queued builds and stop them from screwing each other up.

Fix AppVeyor Blobs

---

ENIGMAsystem/SHELL/Collision_Systems/actions.h
ENIGMAsystem/SHELL/Collision_Systems/collision_mandatory.h
ENIGMAsystem/SHELL/Graphics_Systems/General/actions.h
ENIGMAsystem/SHELL/Universal_System/Extensions/MotionPlanning/actions.h
ENIGMAsystem/SHELL/Universal_System/Extensions/Paths/actions.h
ENIGMAsystem/SHELL/Universal_System/actions.h

Taking a second to address a couple of regressions introduced by #1128 that cause Mark Overmar's FPS example to no longer build.
* argument_relative should have been in namespace enigma_user in Universal_System/actions.h
* argument_relative should have been in namespace enigma_user in MotionPlanning/actions.h
* argument_relative should have been in namespace enigma_user in Paths/actions.h
* argument_relative should have been in namespace enigma_user in Collision_Systems/actions.h
* argument_relative should have been in namespace enigma_user in Graphics_Systems/General/actions.h
* place_meeting_inst was using the old guard, just had to rename it to what @fundies changed it to
After these changes, Mark Overmar's FPS example successfully builds again and the gameplay works fine:

Fix game global regressions

---

.travis.yml

This fixes the issues with Travis erroring about missing references on checkout. The problem was basically that @JoshDreamland merged two prs at the same time and Travis didn't checkout deep enough to have the commit reference. I originally made the depth 1 as an optimization to make the build faster, guess it doesn't work.
> Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.
https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth

Fix Travis CI Clone Depth

---

ENIGMAsystem/SHELL/Universal_System/object.cpp

Changes tab indentation to two spaces and then applies Josh's fix to object_is_ancestor.

object_is_ancestor fix

---

ENIGMAsystem/SHELL/Universal_System/Extensions/Timelines/About.ey
ENIGMAsystem/SHELL/Universal_System/actions.h

So somebody at YoYoGames obviously dropped the red ball here big time with GameMaker 8. Using the built-in function lists, I can see that `action_set_timeline` was renamed to `action_timeline_set` starting with GM8 and then `action_set_timeline` was removed in GMS 1.4.
I used ActionMaker to confirm that it was in fact originally `action_set_timeline` in the GameMaker 5 libs:
Apparently what they did was create a new action (judging by GM8 libs in ActionMaker) so they could add two parameters onto the action, which is fine for us because we just used default parameters which will work in both cases:
So, ENIGMA was always correct, but we can work around GMS 1.4 for now with a simple define.

Timeline actions workaround for GM8 and GMS

---

ENIGMAsystem/SHELL/Universal_System/object.cpp

Polygonz should have used `object_idmax` in 182e024ecbd8f28a8976545a117fb5fc43d83175 not `object_count` like all of the other `_exists()` functions. I wasn't sure if it's correct to check if the obj id is larger than zero though... none of the other `_exists()` functions do that but it seems as though they should. Either way, we need to later on get rid of all this duplicate code by solving #1125.

Fix object_exists

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.h
ENIGMAsystem/SHELL/Universal_System/estring.cpp
ENIGMAsystem/SHELL/Universal_System/estring.h
ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/win32utf8.h

Enables use of these functions so that UTF-8 can potentially be supported on all Windows functions.

widen() and shorten() can now be used everywhere

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp

Everything supports it except the CreateWindow() which is unnecessary in this case and windowsystem_write_exename() which still needs to get done but idk how to make it support UTF-8. If windowsystem_write_exename() is made to support UTF-8, there will no longer be an error message when you try to run your game inside a path with special characters. I'll need some help with this.

WINDOWSmain.cpp now supports UTF-8

---

ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp

Long story short, user came to the forum and showed us some code that was slower using `ds_list_replace` than arrays with the subscript `[]` operator: https://enigma-dev.org/forums/index.php?topic=2887.
I looked and realized it must be `.erase(...)`'s fault. I sent them this fix and they tested it and confirmed it fixed the issue and Hugar also tested it for me and said the same on Discord.
http://www.cplusplus.com/reference/vector/vector/erase/
> Because vectors use an array as their underlying storage, erasing elements in positions other than the vector end causes the container to relocate all the elements after the segment erased to their new positions. This is generally an inefficient operation compared to the one performed for the same operation by other kinds of sequence containers …

Optimize ds_list_replace

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSbasic.cpp
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALadvanced.cpp
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALbasic.cpp

As I reported in #1207, none of the `*_add` or `*_replace` functions in the sound systems are closing the file handle after they finish reading the data.
**It's very important that I make it clear when we shouldn't close the file handle.**
Right now, we should close the file handle, because we always load the sound data immediately and act as if preload is true. If we later change it to actually have preload do what it's supposed to do, then when preload is false we should not close the file handle. That way there is a file lock to prevent the file from being deleted until we actually load the sound data the first time it is played/or gotten/queried.

Close File Handles for Sound Systems

---

ENIGMAsystem/SHELL/Collision_Systems/BBox/BBOXfuncs.cpp
ENIGMAsystem/SHELL/Collision_Systems/Precise/PRECfuncs.cpp
ENIGMAsystem/SHELL/Universal_System/instance.cpp
ENIGMAsystem/SHELL/Universal_System/instance_planar.cpp
ENIGMAsystem/SHELL/Universal_System/instance_system_base.h

This is me attempting to fix #1208 to behave similar to GM and GMS.
Basically, a few collision and instance functions return `noone` or the `id` of the instance. Because `noone` is `-4` it is treated as true if you put those functions directly in an if statement. So, we want them to return var so that when the return value is cast to boolean it is false when negative (as it should be in GML). We typedef `instance_t` as an alias of `variant` (lighter weight than `var` according to Josh) instead of `int` now so that it's easy to change and clear which functions support this.
This will now make the following work as expected:
```gml
if (instance_find(...)) {
// instance was found
}
if (collision_line(...)) {
// there was a collision
}
```
Without having to add `!= noone` to the condition. …

Collision Functions/Bool Cast Fix

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSbasic.cpp
ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSsystem.cpp
ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSsystem.h
ENIGMAsystem/SHELL/Audio_Systems/DirectSound/Info/About.ey
ENIGMAsystem/SHELL/Audio_Systems/DirectSound/SoundResource.h
ENIGMAsystem/SHELL/Audio_Systems/DirectSound/include.h
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALadvanced.cpp
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALbasic.cpp
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALsystem.cpp
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALsystem.h
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/SoundChannel.h
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/SoundEmitter.h
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/SoundResource.h
ENIGMAsystem/SHELL/Audio_Systems/OpenAL/include.h

I am continuing this from #1219 to pave the way for future work on these two systems (OpenAL and DirectSound). All I did was run the clang formatting tool using the `.clang-format` settings on the two directories for `*.h` and `*.cpp` files and then open each file to check it looked good.
```bash
clang-format -i -style=file *.cpp
clang-format -i -style=file *.h
```
This formatting was an utter mess as far as tabs and spaces mixture (I know Graphics systems are really bad too). The messed up formatting made it really hard for me to even do #1219. Maybe, after we do all this, we'll configure a stylecheck for the repo too to prevent this stuff from happening again.
I know formatting changes shouldn't break anything, but I just don't trust the CI enough, so I ran the `sound_replace` tests as …

Audio System Clang Tool Reformat

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3ModelStruct.h

I don't know how this one slipped through the cracks because I swear I tested to make sure OpenGL3 was still building on #1226. For that matter, Travis also told us it was still building. Anyways, after this change I can run the FPS example again with GL3 (there is still the problem of no fog though, but that has been that way).
```bash
In file included from Graphics_Systems/OpenGL3/GL3model.cpp:18:0:
Graphics_Systems/OpenGL3/GL3ModelStruct.h: In member function 'void enigma::Mesh::Draw(int, int)':
Graphics_Systems/OpenGL3/GL3ModelStruct.h:829:31: error: invalid conversion from 'const GLvoid* {aka const void*}' to 'void*' [-fpermissive]
#define OFFSETE( P )  ( ( const GLvoid * ) ( sizeof( GLuint ) * ( P         ) ) )
~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```

Fix OpenGL3 for newer glew

---

.travis.yml

I didn't realize the Mac test stopped passing in #1226 because we allow it to fail. We just need to install glew through brew.
I added this to the announcement too:
https://enigma-dev.org/forums/index.php?topic=2894
The second Mac job fails because of #1230 and is unrelated to this.

Install glew for Mac in Travis

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9draw.cpp

This is a simple one, there was no need to delete the bitmap data because we don't allocate it, it's just a cast into the buffer Direct3D9 allocated. By releasing the destination and back buffers, we are able to clean up the bitmap data we read.
This stops the Wild Racing game from crashing upon start when using the Direct3D9 graphics system. It at least launches, but does not draw anything except the skybox after starting - yet. Regardless the crash is fixed fully though.

Fix draw_getpixel crash in DX9 caused by double-delete

---

ENIGMAsystem/SHELL/Universal_System/Extensions/MotionPlanning/motion_planning.cpp

Hugar showed me one of his build logs with the motion planning extension enabled where I noticed the following warning:
```
Universal_System/Extensions/MotionPlanning/motion_planning.cpp:42:5: warning: type of ‘collision_rectangle’ does not match original declaration [-Wlto-type-mismatch]
int collision_rectangle(cs_scalar x1, cs_scalar y1, cs_scalar x2, cs_scalar y2, int obj, bool prec /*ignored*/, bool notme);
^
Collision_Systems/Precise/PRECfuncs.cpp:149:20: note: return value type mismatch
enigma::instance_t collision_rectangle(cs_scalar x1, cs_scalar y1, cs_scalar x2, cs_scalar y2, int obj, bool prec, bool notme)
^
./Universal_System/instance_system_base.h:27:19: note: type ‘struct instance_t’ should match type ‘int’
typedef variant instance_t;
^ …
```

Fix Collision Function Return Type Mismatch in Motion Planning Extension

---

ENIGMAsystem/SHELL/Universal_System/highscore_functions.cpp

This is to fix the other warning in the log Hugar shared with me. This is a continuation of #1256 and I am fixing it the same way, by including the general header that already declares the functions and removing the redundant declaration from the source.
Just worth mentioning I see @JoshDreamland was the one responsible for the "holy shit" comment: https://github.com/enigma-dev/enigma-dev/commit/5200d9f7fc018bcf556bfe89bd0a2f22201e583f#diff-765c74df0d2f6fac085f83fb959e38ceR176
So I assume he wanted this moved before we had a general header setup and it wasn't easy at the time for him to do that.
```bash
Universal_System/highscore_functions.cpp:176:5: warning: ‘string_width’ violates the C++ One Definition Rule  [-Wodr]
int string_width(variant str);
^ …
```

Fix warnings in highscore functions

---

CommandLine/emake/Proto2ES.cpp

When I wrote the `AddImage` method in Proto2ES, I just copied and pasted the image reading code we had from universal without realizing it does power of two resizing. Proto2ES actually doesn't need to do this because it is taken care of by the image loading module in Universal either when loading images from the exe or through `*_add` functions. The LGM-ENIGMA plugin also does not resize images to a power of two, it simply passes them at the original size, and so Proto2ES should do the same.
This fully resolves background repeating issues as observed in the Game of Life example by Mark Overmars.

Fix Proto2ES Image Loading

---

CommandLine/emake/Proto2ES.cpp

This fixes #1254 to the fullest. @JoshDreamland correctly discovered for me that the block size was being written incorrectly. I traced it down to my copy of `zlib_compress` in Proto2ES not returning the outsize with the correct size of the compressed data.
With this one fixed, I have added a new game to my list of emake projects that now work. The platforming engine from the EDC: https://enigma-dev.org/edc/games.php?game=69
Game exhibiting problems: [platform_engine.zip](https://github.com/enigma-dev/enigma-dev/files/2079012/platform_engine.zip)
```
./emake "C:/Users/Owner/Desktop/GMGames/platform_engine.gmk" -o /tmp/test.exe -r -c Precise
```

Fix Proto2ES Zlib Compression

---

ENIGMAsystem/SHELL/Platforms/Android/AndroidWindow.cpp
ENIGMAsystem/SHELL/Platforms/Cocoa/CocoaWindow.cpp
ENIGMAsystem/SHELL/Platforms/General/PFwindow.h
ENIGMAsystem/SHELL/Platforms/None/fillin.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
ENIGMAsystem/SHELL/Platforms/iPhone/CocoaWindow.cpp
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/BulletDynamics/BulletRigidBody.h
ENIGMAsystem/SHELL/Universal_System/Extensions/BulletDynamics/BulletShape.h
ENIGMAsystem/SHELL/Universal_System/Extensions/BulletDynamics/BulletSoftBody.h
ENIGMAsystem/SHELL/Universal_System/Extensions/BulletDynamics/BulletWorld.h
ENIGMAsystem/SHELL/Universal_System/background_internal.h
ENIGMAsystem/SHELL/Widget_Systems/General/WSdialogs.h
ENIGMAsystem/SHELL/Widget_Systems/None/nowidget_impl.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/widgets_mandatory.h

This pull request attempts to resolve #928 
The decision we are making here is that the following functions should accept constants, literals, and variables that are not of string type. We are choosing these functions because they seem to be the most common ones that people tend to do this with, but are leaving the rest as still accepting only string (requiring `string(var)` to be passed) since they usually involve more complex messages anyway.
1) show_message
2) window_set_caption (because e.g. `window_set_caption(fps)` is common)

Overloads for String Functions

---

ENIGMAsystem/SHELL/Widget_Systems/TinyFileDialogs/dialogs.cpp

I had to fix the function signature for fervi to use the system. He was getting undefined reference errors because the signature did not match the declaration. This happened because I recently changed the signature in #1273 and nobody merged branch master into TFD, so it went unnoticed. This fixes it.

Fix show_message in TFD system

---

ENIGMAsystem/SHELL/Widget_Systems/TinyFileDialogs/dialogs.cpp

Prior to this change, TFD would replace double quotes with single quote apostrophes, but now, proper escaping has been added so that double quotes can be used in strings as normal without closing the string prematurely.

TFD now supports double quotes in strings

---

ENIGMAsystem/SHELL/Widget_Systems/TinyFileDialogs/dialogs.cpp

I noticed I replaced the quotes with quotes using escaping, before checking the existence of the path with stat(), and the existence of the file with access(), this means if you used quotes in your string for the fname or dir arguments, the file and path will not be recognized. To fix this, I called string_replace_all() on fname_or_dir after stat() and access() instead.
I also reorganized the functions around and reformatted the way the FileFilter class was written, without changing its behavior.

fix for get_open/save_filename_ext()

---

Compilers/Linux/AndroidSym.ey
Compilers/Linux/clang.ey
Compilers/Linux/clang32.ey

This pull request addresses some mistakes fundies made that were merged as part of #1278 
Although the EYAML reader is case insensitive for key names, because it converts them to lower case, I decided to change `Exe-Vars` to `EXE-Vars` in `clang.ey` and `clang32.ey` to match the other Linux Compiler ey files anyway. I also added the required prefix back to `AndroidSym.ey` which fundies removed for some reason.

Fix mistakes in Compiler ey files

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp

Took me a while to track this one down, but I went on a hunt to find out why the game icon was no longer working. I tracked it down to 15fce1a894de6c2f5ec1b4443fd1cdb5a02dbf9c which was merged from #1259.
In case you can't spot the issue, fundies did not keep the initialization of `hInstance` inside `WinMain` where it's actually a parameter. Hence, he had it just being set to its uninitialized self, which means it was undefined behavior. To prevent this from being broken again, I've added a comment that will make any contributor think twice before breaking it in the future.

Fix Game Icon For Win32

---

CommandLine/testing/main.cpp

This is a fix to #1299 for a mistake we made. `::testing::InitGoogleTest(&argc, argv);` apparently mutates its first parameter which was screwing up fundies check to see if we passed any parameters **_AT ALL_** to the `ci-regression.sh` script. This must be merged before #1305 or it will continue to build the outdated master's test harness.

Regression Tests Fix

---

CommandLine/testing/Platform/TestHarness-X11.cpp

Alright, I made a slight mistake in #1310 and this pull request fixes it.
I noticed it on the integration build:
https://travis-ci.org/enigma-dev/enigma-dev/jobs/403311028#L7196
```
`WORKDIR=/home/travis/build/enigma-dev/enigma-dev/--workdir=/`
```
I just forgot to prefix the right-most argument to the ternary assignment of local workdir with `tc->`, since I obviously don't want to initialize the local `workdir` to its uninitialized self.

Continuous Integration Workdir/Codegen Fix

---

.travis.yml
CommandLine/testing/main.cpp
ci-regression.sh

I am attempting to fix the 6% code coverage issue that started in #1313 or #1310.
We can see that the issue is caused by uploading only 10 code coverage reports when we are running 11 tests in total. This is the result of the fact that we only upload code coverage reports in the main yaml after the first instance of the test harness returns (which doesn't look in the regression tests directory at all for `*.info` files).
https://travis-ci.org/enigma-dev/enigma-dev/jobs/404073149#L7628

Fix Code Coverage For Regression Tests

---

CommandLine/testing/SimpleTests/math_test.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/var4.cpp
ENIGMAsystem/SHELL/Universal_System/var4.h
ENIGMAsystem/SHELL/Universal_System/var_array.cpp
ENIGMAsystem/SHELL/Universal_System/var_array.h

Ok, a couple of changes here to address #1331 as well as add other functions I think are useful.
* Added `array_equals` from GMS
https://docs2.yoyogames.com/source/_build/3_scripting/3_gml_overview/arrays/array_equals.html
* Added `array_copy` from GMS
https://docs2.yoyogames.com/source/_build/3_scripting/3_gml_overview/arrays/array_copy.html
* Added `array_create` from GMS
https://docs2.yoyogames.com/source/_build/3_scripting/3_gml_overview/arrays/array_create.html
* Added `array_create_2d(length, height, value)` that is unique to ENIGMA
* Removed old comments about overloading `std::array` that I added since they are no longer relevant.
* Fixed the 2d var array constructor that I apparently never noticed was initializing backwards. It caused `array_create` not to work right after I …

Array Tests & Improvements

---

ENIGMAsystem/SHELL/Bridges/Cocoa-OpenGL1/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Cocoa-OpenGL3/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp
ENIGMAsystem/SHELL/Bridges/None-None/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/xlib-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp

As I described in #1336 this has been a while coming too. I first removed all traces of `room_caption`, `window_set_caption`, and `update_mouse_variables` from all bridges. Then I added them both to the generic `main()` and the caption seems to continue behaving as it always did.
I tested, specifically, the game of life example, which required the mouse update be added to `main()` as well, that's how I knew it was still required. Without that the game was not recognizing any mouse clicks.

Remove Room Caption/Mouse Update From Bridges

---

ENIGMAsystem/SHELL/Graphics_Systems/None/include.h

I'm silly, I know. I forgot about the `None` graphics system in #1333 when making a single general include header and this pr fixes it.

Use General Include for None Graphics System

---

CommandLine/emake/OptionsParser.cpp

This one has really been getting on my nerves, I know we still need settings support, but I need this fixed for now. It has caused me to screw up a commit a couple of times now by having all the codegen stuff in my ENIGMA clone. I simply use `getenv` to expand `LOCALAPPDATA` which is the same place LGM defaults to.

Emake Default Workdir Fix for Windows

---

CommandLine/testing/Makefile

Ran into one more issue with the test harness and drawing tests while working on #1350. That was a new drawing test I was adding which should have only been run on the pull request, but it was being run twice. It was being run on the pull request and on master (which new tests should not be run on).
The reason this occurs now with new tests is because the binary of the cpp still exists until you make clean. When we do the git checkout, the cpp file is removed, but the binary remains. After discussing this with Rusky and Fundies on Discord, I decided upon this fix to just always force relinking of the binaries for the test harness since it's least pita. If you would prefer it be done another way, please tell me.
When I tested this change in #1350, Travis did then correctly report the 3D …

CI Regression/Test Harness Binaries Linking Fix

---

.vscode/settings.json
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11surface.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9surface.cpp
ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLsurface.cpp

Fixed GL1, DX9, DX11 and NONE not compiling with surface_create due to new parameters
Surface create on the newer renderers has
`int surface_create(int width, int height, bool depthbuffer, bool stencilbuffer, bool writeonly)`
However, with older renderers stencilbuffer and writeonly are not present. Quick workaround allows games to be compiled as normal using these renderers.
The following line is now present in the 4 listed renderer's surface cpp files, adding the two bool parameters.
`int surface_create(int width, int height, bool depthbuffer, bool, bool)`

Fixed GL1, DX9, DX11 and NONE not compiling with surface_create

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp

The generalization of the main loop for SDL introduced a regression I finally caught reviewing my benchmark in #1289. The timing variables should be initialized just before input and before ANY user events (e.g, game start, room start, or the create event in my case) are fired at all, otherwise `get_timer` is completely inaccurate. 
This occurred on Win32  where we don't query whether to use the high quality performance counter until the timing is initialized. All of the microsecond times I reported in my benchmark for #1289 are basically inaccurate to within 1/1000th of a microsecond. I am going to have to redo the entire benchmark now with this patch to see the actual difference.
I caught the mistake by wondering why none of my changes to the new model creation (in an effort to speed it …

Timer Initialization and Accuracy Fix

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GStiles.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GStilestruct.h

Simple change, I was getting annoyed seeing the following warning in the tiles sources.
```bash
Graphics_Systems/General/GStiles.cpp:39:21: warning: '{anonymous}::bkinxcomp' defined but not used [-Wunused-variable]
enigma::bkinxop bkinxcomp;
^~~~~~~~~
```
The reason was because when I moved `bkinxcomp` to an anonymous namespace, I forgot to remove the namespace enigma extern for it in the header. This pull request just safely moves all of it to the anonymous namespace since it's not used outside of these sources or in any other translation unit. I also changed the parameters to be const references.

Tiles Comparison Functor Warning Fix

---

ENIGMAsystem/SHELL/Widget_Systems/TinyFileDialogs/linux.cpp

Zenity requires double underscores to represent a single underscore in a string. Therefore, this change replaces all underscores in a string with double underscores, so that the correct string will be used and displayed in the dialogs.

Added support for underscores in strings

---

.travis.yml
CommandLine/testing/GitHub-ImageDiff.sh
ENIGMAsystem/SHELL/Graphics_Systems/General/GSstdraw.cpp

For various reasons, we are just going to make graphics changes not fail the build. Sometimes graphics changes are good, it all depends on context. Further, we are going to attempt starting xvfb and xfwm in the `before_script` phase to see if it alleviates some of the false positives that keep pissing everybody off.

Regression Tests False Positive Fixes

---

CommandLine/libEGM/Makefile
CommandLine/libEGM/egm.cpp
CommandLine/libEGM/filesystem.cpp
CommandLine/libEGM/filesystem.h
CommandLine/libEGM/gmk.cpp

Uses 5 random digits (unique to each emake process) prefixed to the string "gmk_data" with a postfix of the increment of the file number being written. Fundies wants the prefix so he can sort with the file manager. This version does not rely on any POSIX functions or non-standard C++ features.

File System Cleanup and Boost Fallback for libEGM

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSvertex_impl.h

Minor oversight on #1355, I should have initialized dynamic to false by default, which was what I intended. Nothing at all is actually using the dynamic flag yet anyway.

Vertex Buffer Should Initialize Dynamic To False

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel_impl.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSvertex.cpp

Hahaha, that one thing that I thought would never bite me, bit me. I am talking about empty primitives and such things as ending a vertex format without beginning one. I found this in the Minecraft-esque game that somebody made in GM and used to work in ENIGMA. As a result of this, I decided to go the extra mile and add more debugging messages for graphics, because they are really useful and we need them.
After some deliberation, I did decide to make it a non-fatal error message to begin and end a primitive without specifying any vertex data when you don't specify a valid format. It's effectively a no-op, but the user is still being inefficient and misusing the API by doing so (and there's absolutely **zero** reason to do this).
This is a fix to what you would call a regression that was …

Empty Primitives Fix & Better Graphical Debug Messages

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel_impl.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSvertex.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSvertex.h

I was curious to try out what Josh suggested in #1365 because I had already thought about it once. Turns out it worked and gives some great benefits.
* `current_primitive` of Model is now in the same allocation avoiding unnecessary memory allocation and overhead
* `currentVertexFormat` global is now stack allocated to avoid allocation overhead
* Calling `vertex_format_end` without calling begin is no longer an error
* Calling `vertex_format_begin` twice is no longer an error, but less efficient because `currentVertexFormat` will be reinitialized twice
* Calling `d3d_model_primitive_end` without calling begin is no longer an error
* Calling `d3d_model_primitive_begin` twice is no longer an error, but less efficient because `current_primitive` will be reinitialized twice
* …

Graphics Primitive Stack & Same Allocation Optimization

---

.travis.yml
Makefile
ci-regression.sh
shared/lodepng/Makefile

Alright, I am sick of all the issues from us not doing a make clean before checking out master. This bites us every time we want to add or remove a source file or even a header because make sucks. I am not only adding the make clean to stop all this nonsense but also adding a second command line argument to the `ci-regression.sh` script to pass the number of jobs. Because of that, this shouldn't have much of an effect on the regression test job time.
This needs merged prior to #1367 so that pr doesn't fail CI tests.
* No longer call make for the test-harness job during the install phase at all. It's completely handled by the `ci-regression.sh` script now. I hadn't noticed this before or I would have removed it sooner (the second make is just redundant and time costly).
* Pass 4 as the …

Clean Regression Builds

---

ENIGMAsystem/SHELL/Widget_Systems/TinyFileDialogs/linux.cpp

+= makes the string display twice and does not modify the first iteration of it properly.
= the string displays once and gets modified correctly.
Silly me.

Replaced += with =

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSvertex.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSvertex_impl.h

This pull request can be considered a continuation of #1366. We want declaring a vertex format to be extremely fast.
Alright, I found the final nugget that has been holding us back, and it was `vertex_format_begin`. With this change, I get the same performance boost as I do by specifying the format up front but without requiring as many changes. As my comment states, the issue is basically that each time we begin a new vertex format, if I call the default constructor, that gives us a new vector and requires a whole new allocation. Hence, we can just clear the flags and reset the vertex format manually to speed it up for dynamic primitives.
This pull request basically gives the same results as #1369. We may still want to also merge that pr later though because common vertex formats are …

Vertex Format Reset Optimization

---

CommandLine/libEGM/gmk.cpp

So I guess MSVC and MinGW/GCC have different order of evaluation. With this change, the MSVC build of RadialGM can load GMK projects successfully. Let's get this merged as quickly as possible.

GMK Byte Evaluation Order Fix

---

ENIGMAsystem/SHELL/Widget_Systems/TinyFileDialogs/dialogs.cpp

The "fname" and "dir" arguments to these functions were previously broken and unusable on Mac OS X and Linux. This pull request fixes the issue.

Fixed get_open/save_filename_ext()

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp
ENIGMAsystem/SHELL/Bridges/Win32-Direct3D11/Makefile
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11TextureStruct.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11matrix.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11surface.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11vertex.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/Makefile
ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3matrix.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3matrix.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3vertex.cpp
appveyor.yml

The goal here was to get Direct3D11 actually working with some texturing support and all. In order to do this I had to use GLM to implement the matrix functions. The idea is that once we get matrices working perfectly in this system, we can move them to general and use them for all of the graphics systems.
* Moved render target initialization logic to a helper method to properly implement the window resized handling in the D3D11 bridge
* Implemented vertical synchronization functionality for D3D11
* Implemented all projection/transform/transform stack functions for D3D11 using GLM
* Fixed `graphics_create_texture` to use BGRA format and deleted unused code for D3D11
* Added `getDefaultWhiteTexture` helper to implement `texture_set_stage` behavior. This is so that sampling unset textures …

Direct3D11 Improvements and Matrices Using GLM

---

appveyor.yml

This change uses the pacboy bash script, instead of pacman, to find and install the packages in our AppVeyor build. The reason for this change is to make the lists of dependencies easier to read. I have already changed ENIGMA's wiki to also use pacboy because the repeated `mingw-w64-x86_64-` is really hard to look at.
https://enigma-dev.org/docs/Wiki/Install:Windows#Dependencies

Use Pacboy to find MSYS2 Packages in AppVeyor

---

.travis.yml

This follows the AppVeyor job variables cleanup in #1386 to do the same thing for Travis. After I noticed how much easier it makes the UI as well as the yaml source to read, I really wanted to get it done for Travis.
It's very obvious looking at the following image that it's much easier with this change to discern which job is doing what in the UI now.

Cleanup Travis Matrix

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp
ENIGMAsystem/SHELL/Platforms/xlib/XLIBmain.cpp

This fixes the event handling issues and input lag reported in #1375 for Windows and Xlib. This has been bugging everybody and I finally tracked it down to 15fce1a894de6c2f5ec1b4443fd1cdb5a02dbf9c (#1259) where fundies generalized the main loop.
The mistake made was very minor, when PeekMessage was handled, fundies continued to return 0 from `handleEvents` which allowed the regular game events to continue being processed. We actually need `handleEvents` to remove all the native messages from the queue. Only when all native events are cleared should the main loop proceed to handle ENIGMA's events.
https://github.com/enigma-dev/enigma-dev/commit/15fce1a894de6c2f5ec1b4443fd1cdb5a02dbf9c#diff-a46c22f2e9ae6a84c51d776c9e2b7308L326
https://github.com/enigma-dev/enigma-dev/commit/15fce1a894de6c2f5 …

Fix Event Handling/Input Lag for Win32 and Xlib

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11matrix.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9matrix.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSd3d.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSscreen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/None/NONEd3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.cpp
ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLd3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLmatrix.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3matrix.cpp

This one is going to be a little bit complicated to explain, but from my testing, `d3d_set_perspective` in GM8.1 and GMSv1.4 should **never** take effect until the next frame/`screen_redraw`. It should also only take effect if we are actually in d3d mode meaning that `d3d_start()` has been called.
The newer GMS manual describes this function as if it affects the "default" room projection because it mentions the view:
https://docs.yoyogames.com/source/dadiospice/002_reference/drawing/drawing%203d/3d%20setup/d3d_set_perspective.html
>This turns on (or off) perspective projection. With a perspective projection instances that have a greater depth will appear smaller, so when the depth is 0 it is equal to the original size and the viewpoint for the camera is placed at a distance above the …

Fix 3D Perspective Mode

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11colors.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9colors.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GScolor_macros.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLcolors.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLd3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3colors.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3d3d.cpp

This is bullshit, so I finally found the cause of what actually was wrong with the lighting. It appears as though I made some glaring mistakes in #1265 by overlooking sources that redefined the color macros to obtain them as floats. This pull request fixes those mistakes by adding a second set of color macros that will clamp the color component between 0 and 1 for functions that work with color components in that format.
* Replaced `D3DCOLOR_COLORVALUE` (4-component float -> D3DCOLOR) with `D3DCOLOR_RGBA` (4-component int -> D3DCOLOR) in certain areas where I already had integer (0-255) color components
* Replaced `COL_GET_R` with `COL_GET_Rf` anywhere we divide by 255.0 so that isn't duplicated everywhere
* Removed calls to `SetMaterial` in D3D9 because they are not actually necessary to …

Color Macro Fixes

---

ENIGMAsystem/SHELL/Universal_System/Extensions/MotionPlanning/motion_planning.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/Paths/path_functions.cpp

This is just a small change I am pulling from #1369 since I am unsure about the other changes in that pull request but do not want this part to be forgotten. All this change does is delete the redundant declaration of drawing functions in the Motion Planning and Paths extensions. In place of the deleted declarations I have instead included the relevant general graphics systems headers which declare the functions. This prevents future issues from occurring that may stem from violation of the one definition rule.

Cleanup Motion Planning & Paths Graphics

---

CommandLine/emake/Server.cpp

This is just a simple fix to the while loop in the server that gets us compiler resources. Without this change the loop never ends after printing all the keywords that I want to populate in the Scintilla script editor. It was just printing empty strings after the resource end. This fixes that and makes it like the `--list` option which was already working correctly.

GRPC Resources Fix

---

CommandLine/emake/Main.cpp
CommandLine/emake/OptionsParser.cpp
CommandLine/emake/OptionsParser.hpp
CommandLine/emake/Server.cpp
CommandLine/emake/Server.hpp
CommandLine/protos/server.proto

Simple change here that's needed for additional RGM features. I am exposing the functionality of the `--info` option of emake as an RPC method for any frontend that is interacting with an emake server.
The new RPC method is called `GetSystems` and it returns information about all of the major systems and all of their subsystems structured as proto messages. The RPC method takes no arguments and there is a reason for this. I expect that the client only wants to obtain and update this information infrequently, and when it does so it wants to update things dependent on the information of other systems at the same time. So not only is there not a need to obtain information about just one system, I think it would be inefficient to allow that. The client is expected to request information of …

GRPC Methods for System Info

---

CompilerSource/filesystem/file_find.cpp
CompilerSource/filesystem/file_find.h
CompilerSource/settings-parse/crawler.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSfilemanip.cpp

Ok I am very feisty about this one because people keep telling me it thinking it's a problem even though it really isn't. So the platform inspection, it has false positives because Josh's immature file find does silly stuff like return files and not directories on Win32 and it totally ignores the passed file attributes. However, I would have fixed this by just fixing the file find if that were the only problem. It also has issues because it returns the current directory and the parent directory as `.` and `..` which screws up the platform inspection.
The way I did fix this was by adding `file_exists` with a Win32 and POSIX implementation to `CompilerSource/filesystem/`. Yes, these are based on the ones in the engine, and I am not really concerned about duplicating the code at the moment. …

Fix Platform Inspection False Positives

---

ENIGMAsystem/SHELL/Collision_Systems/BBox/include.h
ENIGMAsystem/SHELL/Collision_Systems/Precise/include.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.h
ENIGMAsystem/SHELL/Universal_System/Extensions/MotionPlanning/mp_movement.h

I went in here to try to cleanup up a few of the JDI `ERROR` messages when starting up. I only actually managed to fix one of them but I did cleanup some other include mistakes we've made.
This is the message that this pull request fixes, but there's still 2 of the 3 occurrences of it left with the exact same message.
```
ERROR(ENIGMAsystem/SHELL//Universal_System/sprites_internal.h,22,92): #error This file includes non-ENIGMA STL headers and should not be included from SHELLmain.
```
1) Removed BBox/Precise implementation header includes from each system's respective `include.h` where they didn't need to be included. I think I may have been the one who originally made the mistake while I was moving their `enigma_user` function declarations to `Collision_Systems/General`.
2) Moved the …

Cleanup a few includes causing JDI errors

---

CommandLine/emake/Server.cpp

So, I went in here looking for why RGM was printing all the keywords to its output window with messages like "Attempt to use X which is Y as Z." I looked and it's apparently because the `GetResources` RPC I wrote is attempting to access overloads and the function signature for globals and other non-function resources. The simple fix here is to just nest the arg count stuff under a check of the is function just like the `--list` command does and `lgmplugin` does.
These are the messages this pull request gets rid of in RGM:

Fix GRPC Access of Non-function Resources

---

ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.cpp

The file dialog functions had an issue with setting the filter to "All Files" using asterisks on OS X. Anyways, this pr fixes it.

Fixed "All Files (*.*;*)" File Filter on Mac

---

CommandLine/emake/Proto2ES.cpp
CommandLine/libEGM/gmk.cpp
CommandLine/protos/Background.proto
CommandLine/protos/Sprite.proto

This is a remake of #1279 that we were just discussing. Josh wants to fix it this alternative way, by deprecating this kind of transparency and for now fixing it in the GMK reader only. The whole "transparent" option was deprecated sometime after GMK version 710. All later versions of GMK used BGRA images, so I only had to add support for it in the BMP reader.
* Explicitly initialize `transparent` to false in Proto2ES for safety.
* Accept `transparent` as a parameter to the BMP temp file writer in GMK.
* Remove the `transparent` field from Sprite & Background protos.
* Reorder all the fields of the Sprite & Background protos to have consecutive field numbers.

libEGM GMK Transparency Fix

---

CommandLine/emake/OptionsParser.cpp
CommandLine/emake/Server.cpp
CommandLine/protos/server.proto

This is a continuation of #1402 in which I am proposing a fix for the compiler targets. Because all of the combos I am using in RGM use name/id, and because I include compilers in that group, I need the compilers to have valid ids in order to select them. This is a bit tricky, because unlike the SHELL systems, compiler descriptors have historically been identified using their filename minus the extension (so Windows/gcc.ey has an identifier "gcc" in LGM and emake). The simple solution I am proposing here is to use this id, which emake already has, if neither "id" nor "identifier" appears in the compiler descriptors ey to provide the identifier.
* Removed comments asking why id/identifier is different between extensions and systems. I actually fixed this on master at some point, because …

Aliases for System Info 

---

CommandLine/emake/EnigmaCallbacks.cpp
CommandLine/emake/EnigmaCallbacks.hpp
CommandLine/emake/EnigmaPlugin.cpp
CommandLine/emake/EnigmaPlugin.hpp
CommandLine/emake/Main.cpp
CommandLine/emake/Server.cpp
CommandLine/emake/Server.hpp
CommandLine/protos/Makefile
CommandLine/protos/server.proto

Alright so the basic goal here was to get the emake server forwarding output to the client. This way it's possible to get the output when emake is running on a remote host. This has been accomplished by threading the game compile and sending a stream of log messages back to the client. For now the log messages are only taken from the IDE frame append callback and read from the IDE output redirect file.
* Added an accessor to `CallBack` to get the current progress status of the compile.
* Added accessors to read the log message queue from `CallBack` which are synchronized using a semaphore. The design of the accessors is inherently thread-safe, as the user is expected to read the entire log queue and then clear the queue (which unlocks the queue) when they are done reading.
* Added a …

Async Compile & Remote Logging

---

CommandLine/emake/Proto2ES.cpp

Alright, so I got to the bottom of why emake server crashes when it goes to build the same game again. The reason is because Proto2ES holds a bunch of state in static allocated variables. This change fixes it by clearing that state each time Proto2ES is called.
* Made all of the last id variables for each resource type a group of static globals instead of static and local to each resource add method.
* Reset the last id variables to 0 for each resource type at the beginning of `Proto2ES` so the ids are not unnecessarily inflated.
* Cleared the values held by `idMap` and `countMap` so the conversion is not influenced by previous conversions.

Proto2ES Determinism Fix

---

CommandLine/testing/Tests/room_transition_test.gmx/objects/obj_0.object.gmx
CommandLine/testing/Tests/room_transition_test.gmx/rooms/rm_0.room.gmx
ENIGMAsystem/SHELL/Graphics_Systems/General/GSscreen.cpp

Sam has this bug in his game with respect to object following. In his draw event code he accesses variables of view 1 when the current view is view 0. View 1 also happens to be following an object. Brief flickering is caused when restarting because on the first frame we don't have view 1 fully initialized based on the object it follows when the current view is view 0 and he attempts to use its variables to draw a background which "jolts" from the view moving. This is just one of two ways to fix this minor glitch in his game.
This fix here adds a second loop to `screen_redraw` that updates all of the views and their object following before looping the views and firing instance draw events. This fixes the glitch in Sam's game because it means that both view 0 and view 1 are fully updated …

Update View Following Before Draw

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp
ENIGMAsystem/SHELL/SHELLmain.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/Asynchronous/ASYNCdialog.cpp
ENIGMAsystem/SHELL/Universal_System/instance_system.cpp
ENIGMAsystem/SHELL/Universal_System/instance_system_base.h
ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp

This fixes memory leaks as a result of iterating events in various locations. The problem is that the allocated `inst_iter` everywhere are not being deallocated. The solution just uses the `dummy_event_iterator` which is global and has static storage duration that was intended solely for this purpose.

Fix Event Iterator Leaks

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
ENIGMAsystem/SHELL/Platforms/General/PFsystem.h

This adds the `os_browser` constant for checking if the game is being run in a browser. For now it obviously just defaults to `browser_not_a_browser` but it does resolve #1108.
https://docs.yoyogames.com/source/dadiospice/002_reference/operating%20system/os_browser.html

Add os_browser User Global Constant

---

.travis.yml
CommandLine/testing/SimpleTests/math_test.sog/create.edl
ENIGMAsystem/SHELL/Platforms/General/PFthreads.cpp
ENIGMAsystem/SHELL/Platforms/General/PFthreads.h
ENIGMAsystem/SHELL/Platforms/General/PFthreads_impl.h
ENIGMAsystem/SHELL/Platforms/General/PFwindow.h
ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXthreads.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Threads.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.h
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSthreads.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
ENIGMAsystem/SHELL/Platforms/Win32/include.h
ENIGMAsystem/SHELL/Universal_System/GAME_GLOBALS.h
ENIGMAsystem/SHELL/Universal_System/estring.cpp
ENIGMAsystem/SHELL/Universal_System/estring.h
ENIGMAsystem/SHELL/Widget_Systems/DlgMod/dialogs.cpp

Ok, so my goal here is to reduce the amount of pollution in our headers from including things like `windows.h` that result in identifier conflicts and also cause JDI to spontaneously combust. One outcome of these changes is that #1119 is effectively resolved and you can in fact safely assign a script the same name as any Win32 macro or identifier.
* Added a small assignment in the math test for a variable named "CreateFont" which errors without the changes in this pull request. This will prevent people from reintroducing these identifier conflicts again, just like the tests in there for the Bessel functions. However, this won't actually prevent anything until we set up the test harness to run on AppVeyor, since we only run it on Travis with Linux.
* Added a small change to `.travis.yml` …

Include Pollution Cleanup

---

.travis.yml
CommandLine/testing/Platform/TestHarness-X11.cpp
CommandLine/testing/Tests/draw_3d_shapes_test.gmx/objects/obj_0.object.gmx
ENIGMAsystem/SHELL/Bridges/Cocoa-OpenGL1/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Cocoa-OpenGL3/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp
ENIGMAsystem/SHELL/Bridges/None-None/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/xlib-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSscreen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSscreen.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/OPENGLStd.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/OPENGL3Std.cpp
ENIGMAsystem/SHELL/Graphics_Systems/graphics_mandatory.h

This pull request is me addressing some small render state issues all of which are found in the Wild Racing example.
This one is pretty obvious and I actually knew about it before merging the generic primitives changes I made. I was skeptical of how essential it would be though. But considering that `screen_refresh` is really the only guaranteed way in GM to get any drawing outside of the draw event to appear, we have to make this change so that stuff you draw is actually drawn before we present the backbuffer.
This fixes specifically the text on the startup screen of Wild Racing where the controls are drawn. The code is very simple, it just draws the text on the screen, refreshes the screen to present the backbuffer, and then waits for keyboard input.
What I actually changed is very …

Render State Fixes

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9screen.cpp

This one is pretty obvious and allows Direct3D9 to behave more like D3D11 and OGL. Instead of beginning and ending the scene with `screen_redraw` we simply begin the scene as soon as the device is created. We end the scene when we go to present with `screen_refresh` and immediately start a new scene. This allows the user to draw during step or create events, since they will be between `BeginScene`/`EndScene` calls.
https://docs.microsoft.com/en-us/windows/desktop/api/d3d9/nf-d3d9-idirect3ddevice9-beginscene
This does not have any noticeable performance concerns from my observations as my benchmarks continue to perform just fine. As I've said, OGL and D3D11 function this way out of the box anyway. This is why `BeginScene`/`EndScene` were dropped after D3D9, they just complicate the …

Allow Drawing Outside Draw Event for Direct3D9

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel.cpp

This is a fix to address the model translation issues reported in #1456. As I discovered in that issue, through the use of [apitrace](https://github.com/apitrace/apitrace), GM uses a reverse multiplication order to translate the model to the position given. With this fix applied the body of the car is drawn in the correct location with respect to the car's chassis and the terrain height.
* Changed `d3d_model_draw(id,x,y,z)` to not use `d3d_transform_add_translation` because it uses the wrong multiplication order for internal use (it's correct when the user calls it though). Basically, the translation passed to `d3d_model_draw` needs to occur before the user's own transformations, not after.
* Used the transformation stack in `d3d_model_draw(id,x,y,z)` to save and restore the world matrix …

Model Translation Fix

---

CommandLine/testing/Tests/draw_test.sog/create.edl
CommandLine/testing/Tests/draw_test.sog/draw.edl
ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.cpp

This is just a small fix to address #1099 which I have confirmed is in fact a bug. Mark Overmars is very explicit in the manual that `draw_sprite_stretched` "fills" the area as opposed to `draw_sprite` which places the origin at the position specified.
This simple fix just removes the offset of the primitive drawn by the sprite's origin. I've additionally added a test to the drawing test so we know if somebody tries to change it again. Although I do not actually change draw_sprite_stretched_ext here, it is still affected because it's just a wrapper that calls draw_sprite_stretched with its color and alpha.
In my opinion, GameMaker is correct about this behavior as the sprite origin is basically useless when drawing the sprite stretched over an area. I feel this is especially true …

Stretched Sprite Origin Fix

---

ENIGMAsystem/SHELL/Bridges/General/DX9Context.h
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9vertex.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/Info/About.ey

This pull request addresses the Direct3D9 reset issues mentioned in #1455 by using Direct3D 9Ex on supported platforms (Windows Vista or later) and regular Direct3D9 with resources placed in the managed memory pool everywhere else (Windows XP/non-WDDM drivers). GameMaker: Studio v1.4 also happens to be using Direct3D 9Ex on Windows, though I don't know if this was their decision or just built into ANGLE.
This solves the issue because Direct3D 9Ex does not lose textures, buffers, and surfaces as a result of a device reset.
https://docs.microsoft.com/en-us/windows/desktop/direct3d9/dx9lh
> Now with DirectX for Windows Vista, calling Reset after a mode change does not cause texture memory surfaces, textures and state information to be lost and these resources do not need to be recreated. …

Direct3D9 Ex Support

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9screen.cpp

I went digging for the last Wild Racing bug in Direct3D, I wanted to know why the heightmap was flat despite the fact I've already added `draw_getpixel` which it uses to read the heightmap. The issue turned out to be that I was subtracting the view port position from the window region size to obtain the viewport size, instead of just using the viewport size. This fix simply changes the viewport and projection initialization for views in Direct3D9 and Direct3D11 to be the same as OpenGL.
It seems that this mistake has existed ever since 5ae769fabc502730d2c477e2cf631c44f9d1786e where I first added views to Direct3D9. I would like to later move `screen_init` to general sources since the behavior is the same between the two systems. I've opened #1337 to cover that though, for now I just want …

Fix Direct3D Screen View Initialization

---

Compilers/Windows/gcc.ey
ENIGMAsystem/SHELL/Makefile

In master the game icon is not showing when using the SDL platform on Windows. The reason is because we don't link the rc file unless the platform is Win32. This fixes it by checking if the target platform is Windows.
This way seems to me to be the proper way for us to do this so that we can continue supporting cross-compilation correctly. Not only that, consider that we also use `target-platform` to determine whether to write the exe resource file or desktop entry anyway, so it only seems sensible to use the same value to determine when to link said rc file.
https://github.com/enigma-dev/enigma-dev/blob/25f11357ffc6fa184db338a586e6b96e7e64537c/CompilerSource/compiler/compile.cpp#L337

Fix SDL Game Icon on Windows

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
ENIGMAsystem/SHELL/Platforms/None/fillin.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp
ENIGMAsystem/SHELL/Platforms/platforms_mandatory.h
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp
ENIGMAsystem/SHELL/Universal_System/loading.cpp
ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp

Let me start off by explaining an issue that occurs on master since the last time we messed with this. If you show a message in the create event of an object, you will get the dialog but the game itself is not yet visible. This is unlike GameMaker, and actually can be quit annoying as a tiny dialog can be easily lost behind LGM's output window. What makes it even more uncomfortable is that the small dialog is modal, and because the game itself is not visible, there is no taskbar icon to restore the game. This has been a minor frustration I've faced for a couple of months now.
This pull request first dumps all of the `showWindow` crap fundies came up with since it's an obvious duplication of `window_set_visible`. Then I changed the room goto to set the window visible once it has called …

Fix Initial Window Visibility

---

ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp

This has been pissing me off for months ever since we added SDL, I can't believe I let it go on so long. Anyway, long story short, when the game opens on master it's not centered properly. For SDL it's in the top-left corner of my monitor and for Win32 it's centered before the final size is determined, so it's still going offscreen. Simple fix here was to just move the centering after the determination of the window size which fixes it for SDL and Win32.

Fix Default Window Centering

---

ENIGMAsystem/SHELL/Bridges/SDL-Win32/handle.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/widgets.cpp

The Win32 widget system relies on the HINSTANCE for some reason, so this pr provides it so that SDL will build with the Win32 widgets set.

SDL HINSTANCE/Widgets

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix.cpp

It looks like I made a mistake in #1396 when I generalized the matrix functions. Although I started the source new, I did borrow function ideas as well as implementation specifics while writing the new source. I intended to keep everyone on the copyright headers, as I did in the literal header files, but forgot to in the source.

Fix Copyright on Matrix Source

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel.cpp

Alright, because of #1478 I am also double checking a few other copyright changes. Harri's shape building logic was ultimately kept in 4bc76baf118cca0d4540d2aa449c41b46f6f5c36 because it was more efficient. Because he only ever added himself to the model struct header copyright, which was structured differently than what we have now, I missed moving his copyright to the actual model source where his logic appears. His work did contribute to this file, hence he should be kept on the copyright, plain and simple.

Fix Model Copyright

---

ENIGMAsystem/SHELL/Universal_System/Extensions/XTEST/Makefile
ENIGMAsystem/SHELL/Universal_System/Extensions/XTEST/xtest.cpp

The commit f7b04eba038b60507d57d1254c42cd22832e7f87 I made as a part of my original XTest pull request failed to move the include which was lost when @JoshDreamland recreated the pull request in #1463. So yeah, we just need to readd the include here in the XTest extension and I also forgot to link it and it should be good. With these changes, hugar over Discord tells me that it works.

XTest Include & Link Fix

---

ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp

This resolves #1480 and adds the requested functions to the SDL platform. There's currently two small caveats however. The first is that it is not operating system level like the Win32 or XTest extension variants. This means that other applications are not affected by the input simulation. The second caveat is that currently it only works with our keyboard check functions but not `keyboard_string` because the latter uses the text input API and events to know when text has been entered.
https://wiki.libsdl.org/Tutorials/TextInput
It's also possible that `keyboard_check_direct` may not be affected by key simulation of this kind. Finally, our Win32 platform is most consistent with GM8 and GMSv1.4 by having the `keyboard_string` be affected by the key simulation.
```gml …
```

SDL Keyboard Simulation

---

ENIGMAsystem/SHELL/Bridges/General/DX9Context.h
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp
ENIGMAsystem/SHELL/Bridges/SDL-Direct3D9/Makefile
ENIGMAsystem/SHELL/Bridges/Win32-Direct3D9/Makefile

This follows some of the changes in #1487 to bring D3D up to speed with the Windows SDK. DXERR9 was renamed to just DXERR before being totally deprecated and removed by Microsoft.
https://blogs.msdn.microsoft.com/chuckw/2012/04/24/wheres-dxerr-lib/
We were using it to provide i18n error messages to the user when certain operations would fail in the Direct3D9 system. There's a few problems with this. First, we were indiscriminately showing these error messages in run mode and not just debug mode like we do for everything else. Second, the error messages often weren't too descriptive except for ENIGMA developers as opposed to ENIGMA users.
Ideally, I want to remove `DX9Context.h` eventually, which is just adding function call overhead at this point, and bring it more inline with the other …

Remove DXERR Usage From Direct3D

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DIRECTX11Std.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11d3d.cpp

This is a simple change in the same category as #1494 where I am simply reorganizing the depth stencil state to allow toggling of hidden surface removal. Pretty straight-forward, but again I think it should be coming more clear why we would eventually benefit from having some sort of render state manager.
Another concern is performance, even though we are caching the descriptions of the state blocks. Direct3D11 can apparently create up to 4096 instances of the various state block types and will return the same pointer if a similar state is requested. I will need to do more research and benchmarking later though before I will have enough information for us to take advantage of that.
|             | Master | Pull Request |
|-------------|--------|----|
| 3D Cubes    |![3D Cubes …

Direct3D11 Depth Stencil State

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DIRECTX11Std.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11vertex.cpp

Following #1495 and #1494, I am just shifting around the sampler state to allow you to actually toggle the repetition and interpolation. There is more complicated changes to be made here before it becomes GM compatible. GM's internal rendering is apparently not affected by the user's texture address mode (clamp vs repeat), but is affected by the user's texture filter setting (interpolation; where the default is set in Game Settings).
https://docs.yoyogames.com/source/dadiospice/002_reference/drawing/texture_set_interpolation.html
https://docs.yoyogames.com/source/dadiospice/002_reference/drawing/texture_set_repeat.html
Regardless, for now, this at least improves the fps6 game in D3D11 by having interpolation properly enabled on the walls and billboards.
|      | Master | Pull Request | …

Direct3D11 Sampler State

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp

As far as I know, this change should make little fucking difference, but I did confirm, thanks to @rpjohnst, through an apitrace that GMS2 uses a BGRA swap chain format. This doesn't change any games, but we may as well use it for compatibility. This is important for extension compatibility in case people start messing with the device using `window_device` or something to that effect.

Switch Direct3D11 Swap Chain Format From RGBA to BGRA

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11blend.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9blend.cpp

This is going to seem trivial, but long story short, I am making this pull request because GM8 and GMS never change `D3DRS_BLENDOP`. They achieve it by using various combinations of `D3DBLEND` much like our OpenGL system does. The operation itself is always add by default and should remain that way. Later on I can make a blend mode comparison test to run on our CI to ensure this stuff never breaks.
Download Test Project for API Trace: [blend-api-trace-test.zip](https://github.com/enigma-dev/enigma-dev/files/2775237/blend-api-trace-test.zip)
* Remove changes to `D3DRS_BLENDOP` from D3D9
* Remove changes to `blendStateDesc.RenderTarget[0].BlendOp` from D3D11
* Use an array lookup modulo the size for `draw_set_blend_mode` in D3D9
* Fix modulo array size (which should be 11, not 10) for …

Direct3D Blend State Cleanup

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSsystem.cpp

This is a temporary fix for #1508. We are just removing the flag for now because due to an MSYS2 bug, it's currently impossible for us to implement sound effects.

DirectSound Buffer Size Fixes

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11blend.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLd3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLscreen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/OPENGLStd.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGLES/OPENGLStd.cpp

This pull request is just me fixing a few more render states that I noticed are being initialized wrong. I specifically noticed some of these while examining a blend state test by Phantom 107 that I want to adapt for our CI. I am going to provide a modified version here that removes surfaces (because our DX systems have some issues with them).
Download Phantom107 Blend Example: [phantom107-blend-test.zip](https://github.com/enigma-dev/enigma-dev/files/2780157/phantom107-blend-test.zip)
Download Modified Blend Example: [phantom107-blend-test-nosurface.zip](https://github.com/enigma-dev/enigma-dev/files/2780164/phantom107-blend-test-nosurface.zip)
* Moved the enabling of alpha testing to `d3d_start` because GM/GMSv1.4 has it disabled by default and so does D3D/GL. I used apitrace to confirm …

Default Render State Fixes

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix.cpp

I don't know how I missed these functions, but in GM they take degrees and GLM wants radians. I caught this while testing some EDC games, specifically the fake 3D example.
https://enigma-dev.org/edc/games.php?game=66
This change leaves none of the matrix functions taking radians directly, so this should be near the last anomaly with the GM API that's fixed in these sources.
|        | DX11 | DX9 | GL1 | GL3 | GM8 |
|--------|------|-----|-----|-----|-----|
| Master |![Fake 3D DX11 Master](https://user-images.githubusercontent.com/3212801/51566306-3f59f880-1e62-11e9-8171-fee0792fa212.png)|![Fake 3D DX9 Master](https://user-images.githubusercontent.com/3212801/51566340-500a6e80-1e62-11e9-87c3-9d03bc4371ea.png)|![Fake 3D GL1 Master](https://user-images.githubusercontent.com/3212801/51566276-2 …

Fix Top Down Projection Angles

---

ENIGMAsystem/SHELL/Graphics_Systems/General/actions.h

This is a very simple change I caught while reviewing more EDC games. The alpha parameter on the sprite blend action is supposed to be floating point not integer. This effects specifically the Paper Mario battle engine from the EDC.
https://enigma-dev.org/edc/games.php?game=63
I've already corrected the wiki's article for this action too:
https://enigma-dev.org/docs/wiki/index.php?title=Action_sprite_color&action=historysubmit&diff=32045&oldid=26544
| Master GL1 | Pull GL1 | GM8 |
|------------|----------|-----|
|![Paper Mario Battle Engine GL1 Master](https://user-images.githubusercontent.com/3212801/51572926-39214780-1e75-11e9-88ae-5e26a96a45c1.png)|![Paper Mario Battle Engine GL1 Pull](https://user-images.githubusercontent.com/3212801/51572962-5f46e780-1e75-11e9-8185-fd9945b40879.png)|! …

Fix Sprite Color Action

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GStiles.cpp

I am breaking up some of my tile fixes into multiple requests to make them easier to explain. This one is the simplest and easiest to understand. So, one issue with the current tiles is that we are not clearing the metadata vector when switching rooms or when otherwise updating and reloading the tile layers. This leaks, big time, because it means that each room is not only drawing its own tiles but attempting to draw the tiles from all previous rooms. With this change applied, anomalies that were compounding the other issues with the tiles no longer occur and switching between rooms has deterministic tile rendering behavior.

Tile Leak Fix

---

ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.m
ENIGMAsystem/SHELL/Widget_Systems/OsaScript/Makefile
shared/tinyfiledialogs/tinyfiledialogs.cpp

Before this pull request, the dialogs that display an icon would show the default icon for app bundles that have no icon set. This change makes sure the dialog recognizes and uses the icon set for the app bundle by the Info.plist if the file happens to exist, otherwise fall back on the previous behavior.
Applies to all of the following functions, except show_error() due to the limitations of applescript.
show_message():
show_question():
show_error():
get_string():
get_password():
get_integer():
get_passcode():
Unlike the rest of the above functions, show_error() uses a stop sign icon, which in some versions of OS X, specifically the newer ones will show that default "no icon set" icon in the corner regardless, because applescript does not allow the user to change that icon when the stop …

Make Mac dialogs use *.icns file set by Info.plist

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix.cpp

Josh helped me work through the issues with `d3d_set_projection_perspective` so that Project Mario's start screen works again. The issue is that its view matrix should have just been the rotation and translation, and the same is true for `d3d_set_projection_ortho` which we discovered via an apitrace.
With this change, Project Mario's start screen now draws correctly in the OpenGL systems. The Direct3D systems don't render correctly yet because of render state issues (I think z write enable is off, which I'll fix in a separate pull request). I also tested the fix in #1513 to make sure it is still working and saw no regression.

Fix Perspective Projection Matrix

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9screen.cpp

This pull request fixes some Direct3D9 rendering regressions for Project Mario. The specific problem is that vertices that do not have color data are not being rendered when lighting is enabled. Most of the models in Project Mario do not have color or alpha data, but do have texture and normal coordinates.
As is probably obvious, this is not the case with our OpenGL systems or classic GM where the vertices would be simply drawn black. The problem stems from the fact that Direct3D9 uses a default material that's black and transparent where the 0 alpha of the default material cancels out the color of the vertex. To help clarify, you can think of the material as D3D's analog to glColor from OpenGL.
https://docs.microsoft.com/en-us/windows/desktop/direct3d9/materials
>When you create a …

Fix D3D9 Lighting Material

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9d3d.cpp

Alright, so this is another lighting issue that needed to be addressed. GM does normalization of your vertex normals in its lighting computations. It apparently does this in the shader because GM8 and GMSv1.4 do not use the fixed-function lighting according to apitrace. Regardless, the problem here is that our OpenGL1 system is enabling GL_NORMALIZE, but our Direct3D9 system was not enabling the equivalent. There appears to be no alternative, such as normalizing during vertex upload, because we allow the user to transform the models freely using `d3d_transform_*` functions.
There is a noticeable hit for benchmarks, like the 3D Cubes Demo, that have lighting. However, the hit doesn't seem very big, only being about 20~/1700 fps in the 3D Cubes Demo specifically. Regardless, the change does …

Fix D3D9 Lighting Normalization

---

shared/protos/Settings.proto

Split out from #1533 to be more digestible. Tweaked the `Settings.proto` to provide some more sensible defaults for certain fields because they were starting to annoy me. I changed them to be the defaults that LGM and GM already had.

Settings Proto Defaults

---

CompilerSource/backend/GameData.cpp
CompilerSource/backend/GameData.h

This is another one split out from #1533 to define the copy constructors. The basic idea is to copy construct the game proto and flatten the tree into vectors using move semantics.

GameData Copy Constructors

---

CompilerSource/Makefile

I just wanted it to use `$(SHARED_SRC_DIR)` like the other makefiles so it's easier to move the directory later if needed. Split out from #1533.

Clean Compiler Source Makefile

---

CommandLine/emake/Makefile

There was just a few typos in emake's makefile, we should have been using `$(SHARED_SRC_DIR)` in every place so it can be easily changed. Split out from #1533.

Fix Typos in emake Makefile

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSstdraw.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/actions.h

This pull request fixes some remaining issues with the healthbar action and function. The first issue is that the healthbar function was not drawing a border around the background color when the background is shown. The second issue is that the healthbar action function was not mapping the back color parameter to the color constants like the front color parameter. The none option for back color is handled specially by using its value as an argument to the show border parameter. Special thanks to @ProtoLink for helping me fix this, I ended up having to recreate the changes though since he lacks reliable internet to submit the changes himself.
| ENIGMA | GM8 |
|--------|-----|
|![ENIGMA Healthbar Back Color](https://user-images.githubusercontent.com/3212801/52430330-d6b28300-2ad3-11e9-872e-2 …

Fix Remaining Healthbar Bugs

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLbackground.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLsprite.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3background.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3sprite.cpp

This is a recreation of #1522 that has stopgaps for the other sprite and background function and for OpenGL3. This pull request is basically a temporary stopgap for #1423 until I have more time to properly cleanup all of the screen copying. Special thanks to @ProtoLink for helping me fix this issue!
I made a small test for the functions that have been changed here.
Download Test GMK: [screen-copy-test.zip](https://github.com/enigma-dev/enigma-dev/files/2843301/screen-copy-test.zip)
|        | GL1 | GL3 |
|--------|-----|-----|
| Master |![Screen Copy GL1 Master](https://user-images.githubusercontent.com/3212801/52454423-bf968400-2b19-11e9-9c67-c2b416a403af.png)|![Screen Copy GL3 Master](https://user-images.githubusercontent.com/3212801/52454465-cae9af80-2b19-11e9-96c9-e7e26144d7d8.png)|
| …

Screen Copy Stopgaps

---

ci-regression.sh

The CI script inverted the check for the make parallelism being unspecified, and so was not copying it into `MAKE_JOBS`. This check was pointless even if it worked, because if `$2` was unset, `$MAKE_JOBS` would remain unset. Consequently, `make -j$MAKE_JOBS` evaluated to `make -j`, which means "Please saturate my machine with GCC processes." It was not `gcc` spinning up a million `cc1plus` instances; it was `make` spinning up a million `gcc`s, which then `exec`'d `cc1plus`.
Travis' instability is still a little wondrous, but I guess we can continue ignoring that until it becomes a problem again in the future.

Delouse the CI

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9surface.cpp

A few games that use surfaces were having issues in Direct3D9. Basically, when the render target was being reset, I was setting it to the previously set render target instead of back to the normal backbuffer. Since we aren't using a stack, like GMSv1.4 started to do, we obviously end up losing the normal screen render target. I did not want to change us to using a stack yet because that is not backwards-compatible with GM8 and older versions. For now, I've just corrected my mistake in D3D9 and made it behave like GL1.
The following games will now actually render in Direct3D9, where on master they just appear black/blank.
* https://enigma-dev.org/edc/games.php?game=62
* https://enigma-dev.org/edc/games.php?game=67
While I was in here, I ended up fixing the surface pixel read functions too. …

DX9 Surface Target Fixes

---

shared/protos/Object.proto
shared/protos/Path.proto
shared/protos/Room.proto
shared/protos/options.proto

This change basically flags the fields in the protos that are references a resource has to another resource. This is useful for several reasons, but primarily it allows us to deal with `"<undefined>"` within the GMX reader itself by doing a simple comparison.

Resource Reference Proto Option

---

CommandLine/libEGM/filesystem.h

more info here: https://stackoverflow.com/questions/49577343/filesystem-with-c17-doesnt-work-on-my-mac-os-x-high-sierra/49600206

osx clang fix

---

ENIGMAsystem/SHELL/Universal_System/Extensions/libpng/libpng-ext.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.h
ENIGMAsystem/SHELL/Universal_System/image_formats_exts.h

So I am guessing that my include of `<functional>` is what is including `<cstdlib>` and appears to be crashing @time-killer-games pull request #1546.

JDI Image Formats Crash Stopgap

---

CommandLine/Util.h
CommandLine/libEGM/Makefile
CommandLine/libEGM/action.cpp
CommandLine/libEGM/action.h
CommandLine/libEGM/gmk.cpp
CommandLine/libEGM/gmx.cpp
CompilerSource/backend/GameData.cpp
shared/protos/Event.proto
shared/protos/Timeline.proto

I have split these changes out from #1479 to make them easier to digest and integrate. The goal of this pull request is to deprecate the old drag and drop actions by having libEGM convert them to code immediately when a GMK or GMX is loaded instead of having GameData do it at the compile stage. RadialGM has no plans to provide a user interface for the old drag and drop feature. This pull request will allow old games to be run by still providing the actions converted to code for the user.
* GameData does **_NOT_** do the actions->gml conversion now
* GMK/GMX converts the actions->gml with some special handling (they are emplaced at the back of a vector that is passed to `Actions2Code`)
* `Actions2Code` logic was moved from `CompilerSource/backend/Actions2Code.h` to its own source in …

New Code Model

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLvertex.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/OPENGLStd.cpp

From what I discovered looking at #1557, I apparently used the wrong global for checking if the vertex buffer object extension is available. I also discovered that these globals can only be checked after glew has been initialized. So, I had to change it to check for vbo support during graphics system initialize.
http://glew.sourceforge.net/basic.html
>Starting from GLEW 1.1.0, you can find out if a particular extension is available on your platform by querying globally defined variables of the form GLEW_{extension_name}

Fix OpenGL1 Vertex Array Fallback Query

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLvertex.cpp

I noticed after merging #1558 that I had also previously placed a `glBindBuffer` call at the end of the index buffer submit function to unbind an index buffer. This call was being executed even when arrays were being used. This caused @rcobraone further issues in #1557 since his graphics card is failing to provide support for buffer objects and the related functions.

Fix GL1 Fallback for Index Buffers

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLvertex.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/OPENGLStd.cpp

Ok, #1557 led to us discovering one more final change that needs to be made for the fallback to work. If you have an OpenGL version less than 1.5, but the VBO extension is supported, then you must use the special `ARB` postfixed alias of the buffer functions. Special thanks to @rcobraone for figuring this out and providing a reference from Khronos.
I can confirm that, according to the GLEW maintainers themselves, the workaround I am proposing here is completely acceptable and recommended.
https://sourceforge.net/p/glew/bugs/208/
>I think the short answer to this is that your workaround is the recommended way.

Fix GL1 VBO Fallback Aliasing

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DIRECTX11Std.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DIRECTX11Std.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11SurfaceStruct.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11background.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11draw.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11sprite.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11surface.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11textures.cpp

This pull request is part of a family of proposed changes aimed at reducing the compilation warnings in the various graphics systems.
* #1567, #1566, #1565, #1564
This system, Direct3D11, primarily had the most warnings from missing return statements. I tried to use sensible return values for unimplemented functions and `//TODO` comments on these functions. Other than that it just had a few integer comparison warnings and redefinition of the `get_background` macro (which has been moved to Universal_System) just like Direct3D9 did in #1565.

Cleanup Direct3D11 Warnings

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3shader.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3textures.cpp

This pull request is part of a family of proposed changes aimed at reducing the compilation warnings in the various graphics systems.
* #1567, #1566, #1565, #1564
This system, OpenGL3, was the easiest to clean up the warnings for second to OpenGL1.
* The `get_program` shader macro needed to cast the program id to size type to safely compare it with the shader program vector size.
* The `get_program` shader macro needed to format the shader program vector size as a long long unsigned int rather than signed int in the debug print statement.
* The shader types array map had an extraneous `extern` qualification.
* A comparison of the bound shader needed to cast the user shader id to unsigned.
* The `get_texture` macro needed to be of type unsigned (since GL texture ids are unsigned) and …

Cleanup OpenGL3 Warnings

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DIRECTX9Std.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DIRECTX9Std.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9SurfaceStruct.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9background.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9colors.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9draw.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9sprite.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9surface.cpp

This pull request is part of a family of proposed changes aimed at reducing the compilation warnings in the various graphics systems.
* #1567, #1566, #1565, #1564
This system, Direct3D9, was by far the hardest to cleanup for various reasons.
* Many warnings stemmed from missing return statements like #1567. I attempted to use reasonable default return values and placed `//TODO` comments on these functions.
* Some macros like `get_surface` needed to cast the surface id to size type in order to compare it safely with a vector size.
* The `get_background` macro was redundant because we had moved it to `Universal_System` some time ago and it was already being included.
* I had to create an `alias_cast` helper method, with assistance from Rusky, to address type-punned warnings with the fog …

Cleanup Direct3D9 Warnings

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/OPENGLStd.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/OPENGLStd.h

This pull request is part of a family of proposed changes aimed at reducing the compilation warnings in the various graphics systems.
* #1567, #1566, #1565, #1564
For this specific graphics system, OpenGL1, there wasn't actually any warnings to address. However, I did decide to remove two unused variables I noticed lingering around.

Cleanup OpenGL1 Warnings

---

ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALadvanced.cpp

This pull request is a friend of #1573 with the same goal of reducing warnings in the audio systems. Easily enough, OpenAL had only a single warning about an unused variable produced by a call to the `get_sound` macro in `audio_play_sound_on` which was unused because that function simply calls `audio_play_sound_at` using the emitter's location as an argument.

Cleanup OpenAL Warnings

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLd3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3d3d.cpp

The main issue here is that GL3's `d3d_set_hidden` was also toggling `d3d_set_zwriteenable` which it's not supposed to do. This was causing rendering anomalies when I ran Project Mario in GL3. Git blame says I did it in aa45de8915bcfc0d7b40c0629119e07f08211142 and I really don't know why. While I was in here, I decided to also implement `d3d_set_zwriteenable` for D3D11 using the depth stencil description's `DepthWriteMask` which seems to be the DX11 analog to DX9's `D3DRS_ZWRITEENABLE`.
|     | Master | Pull |
|-----|--------|------|
| GL3 |![Project Mario GL3 Master](https://user-images.githubusercontent.com/3212801/53819995-fc974000-3f38-11e9-8575-a33b32d5ad05.png)|![Project Mario GL3 Pull](https://user-images.githubusercontent.com/3212801/53819891-d2de1900-3f38-11e9-9f3b-3ba356ded802.pn …

Fix Hidden & Depth Writing Render State

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11background.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11sprite.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9background.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9sprite.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLbackground.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLsprite.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3background.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3sprite.cpp

I had been planning to do this for a while because I continued running into the vestigial. First, there was no need for each graphics system to duplicate the `get_sprite` macro which, in fact, wasn't even being used anyway. The `get_sprite` macro belongs in `Universal_System` like the `get_background` macro. However, since there's already another non-macro version of `get_sprite` in `Universal_System`, and because this macro wasn't needed, I simply deleted it. I also removed other unused includes that are from the old ENIGMA and have been lingering in these sources for a while.

Cleanup Vestigial Sprite/Background Garbage

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSbasic.cpp
ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSsystem.cpp
ENIGMAsystem/SHELL/Audio_Systems/DirectSound/SoundResource.h

I figured I'd carry on and knock out some more warnings in other systems besides graphics now. DirectSound wasn't too bad honestly, though I see some stuff that will maybe need looked at again later in the context of #1125.
* There were some `get_sound` calls that were declaring unused variables in functions that didn't need them.
* I decided to just add `sound_get_length` here by computing it when a sound is loaded and storing it as a member of the sound resource structure. I just used the same calculation as the OpenAL system, which I hope is correct, but don't really care to test.
* I needed to cast the sound id passed to `sound_replace` to size_t in order to safely compare it with the resources vector size. I also had to do similar for `sound_add_from_buffer` in order to resize the …

Cleanup DirectSound Warnings

---

ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.m
ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.cpp
shared/tinyfiledialogs/tinyfiledialogs.cpp
shared/tinyfiledialogs/tinyfiledialogs.h

Adds the M$ standard abort/retry/ignore error message buttons to show_error() but doing so on all platforms and widget systems. when fatal is true all the buttons abort the game where as only the abort button does that during non-fatal. I'm planning to get rid of the retry/ignore buttons for fatal and retry for non-fatal as they serve no purpose in these contexts, I'm just waiting for KDialog authors to add the --ok-label command line option so that this stuff will be possible for all of our widget systems. It is in their plans to do it, confirmed on their GitHub repository notes. This will allow me to change the single "OK" button to "Abort" for KDialog's fatal error message box, then I'll update all the widgets.
Also reordered the Objective-C function arguments to match the C++ ones in …

cross-platform abort/retry/ignore show_error()

---

ENIGMAsystem/SHELL/Platforms/General/POSIX/main.cpp

readlink does not null terminate, therefore you may end up with a weird value for program_directory prior to these changes...

fix for readlink

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp

This feature was sort of easy to do since I have done it already for D3D9 and I just felt like getting it in here. The function `display_reset(samples,vsync)` just has to release the swap chain, default render target, and the depth buffer and then recreate them with the sample count. We also have to query for the `enigma_user::display_aa` levels in `EnableDrawing` so the user knows what MSAA levels are supported. While I was at it, I decided to change the indentation level to 2 spaces, consistent with the rest of the engine, because I have a hard time reading the code with the extra indentation.
|      | Master | Pull |
|------|--------|------|
| DX11 |![3D Cubes Demo on Master Direct3D11 with 0xMSAA](https://user-images.githubusercontent.com/3212801/54075386-c0cbe580-426c-11e9-97ff-af71fd …

Add Direct3D11 Support for MSAA

---

ENIGMAsystem/SHELL/Bridges/Cocoa-OpenGL1/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Cocoa-OpenGL3/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp
ENIGMAsystem/SHELL/Bridges/None-None/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/xlib-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp

This is pretty obvious, we clearly don't need the definition of the global readonly variable `display_aa` spread out across all the bridges. We can define it in one place, since the user may want to read it even when the target device doesn't support MSAA. I have tested and confirm this does not cause any regressions in the MSAA features, and doesn't seem to cause any compile errors where MSAA is not supported.

Cleanup Redundant MSAA State Definitions

---

ENIGMAsystem/SHELL/Bridges/SDL-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL1/Makefile
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL1/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL3/Makefile
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL3/graphics_bridge.cpp

This has been bugging me for a couple of months why OpenGL had intense z-fighting when using the SDL platform. I finally figured it out and also managed to remove some garbage while I was in here.
This is the one that kept alluding me and is why there was intense z-fighting in 3D games. Apparently, SDL requires you to set the GL attributes before you create a window. Because we were setting them after creating the window, in `EnableDrawing`, we were getting the default 16 bit depth buffer instead of the 24 bit one we requested.
https://wiki.libsdl.org/SDL_GL_SetAttribute
|     | Master | Pull |
|-----|--------|------|
| GL1 |![SDL Master GL1 Zfighting](https://user-images.githubusercontent.com/3212801/54081390-3322e100-42d2-11e9-9dce-8751d189601e.png)|![SDL Pull GL1 No …

Cleanup & Fix SDL's OpenGL Bridge Context

---

CompilerSource/backend/GameData.cpp
CompilerSource/backend/GameData.h
CompilerSource/compiler/compile.cpp
CompilerSource/compiler/components/module_write_backgrounds.cpp
CompilerSource/compiler/components/module_write_fonts.cpp
CompilerSource/compiler/components/module_write_paths.cpp
CompilerSource/compiler/components/module_write_sprites.cpp
CompilerSource/compiler/components/parse_and_link.cpp
CompilerSource/compiler/components/write_defragged_events.cpp
CompilerSource/compiler/components/write_font_info.cpp
CompilerSource/compiler/components/write_room_data.cpp
CompilerSource/compiler/components/write_shader_data.cpp

The Protocol Buffer compiler, protoc, has started appending `final` to generated class definitions as of 3.7. Because of this, our extension classes will no longer build. This removes our dependency on the ability to inherit proto classes, at the cost of using `->` instead of `.` to refer to proto fields from the Data classes.
I've filed a bug about the breaking change as protocolbuffers/protobuf#5869, but do not plan to wait for the resolution, since users are having problems now.

Patch for breaking protoc change.

---

CommandLine/libEGM/CMakeLists.txt
CommandLine/libEGM/Makefile
CommandLine/libEGM/egm-rooms.h
CommandLine/libEGM/egm.h
CommandLine/libEGM/gmk.h
CommandLine/libEGM/gmx.h
CommandLine/libEGM/yyp.h

I ran into build issues trying to update the ENIGMA submodule for RadialGM.
https://github.com/enigma-dev/RadialGM/pull/57
When I did the recent change to convert actions to code immediately (3dd0326edadee06e2895fe3245c338be62da0c57), I made a mistake with one of the includes in `action.h`. I included just the `Event.pb.h` header without its `codegen/` path.
Instead of fixing that mistake, this pull request is proposing that we simply add `shared/protos/codegen/` to the Make and CMake include directories. For one, we don't ever actually include the `.proto` files, so having `shared/protos/` in the include directories doesn't make sense. The codegen includes have a unique file extension of `.pb.h` which distinguishes them from other headers, so there's no chance of getting mixed up. It …

Fix libegm Protos Include Directory

---

CommandLine/libEGM/CMakeLists.txt

Ran into another issue while building RGM with the updated submodule.
https://github.com/enigma-dev/RadialGM/pull/57
The CMake does not include the directory containing `Util.h` like the Make does. Pretty obvious fix here.

Fix libegm Util Include

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp
ENIGMAsystem/SHELL/Bridges/SDL-Direct3D/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp

I started noticing that if we are ever going to add the game settings to SDL we should probably cleanup its window creation. What I did here is very simple. First, I moved the `bool initGameWindow()` definition back to `Platforms/SDL/Window.cpp` so it's in the same place as the other platforms. I left any of the bridge-specific attribute setting in a new helper `init_sdl_window_attributes` specifically for OpenGL. I added a global `unsigned enigma::sdl_window_attributes` so the SDL-OpenGL bridge could specify `SDL_WINDOW_OPENGL`. Finally, I actually added the game settings in `initGameWindow` by appending the SDL window flags for the settings.

Cleanup SDL Window Init & Add Game Settings

---

ENIGMAsystem/SHELL/Universal_System/Extensions/MotionPlanning/motion_planning_struct.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/Paths/pathstruct.cpp
ENIGMAsystem/SHELL/Universal_System/resource_data.cpp
ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp
ENIGMAsystem/SHELL/Universal_System/var_array.cpp
ENIGMAsystem/SHELL/Universal_System/zlib.cpp

Continuing on with the cleanup of warnings until we get rid of them all, here's Universal System.
* The motion planning and path extensions had misleading indentation on a for loop that reallocates their data structure. In both cases, the outer array is being copied to a new outer array, but with the same internal pointers. So I figured out that the delete was intended to go on a new line, outside the for loop, because, again, we're only deleting the outer array not the inner rows. I ran the A* motion planning example by TheExDeus from the EDC to make sure nothing regressed.
https://enigma-dev.org/edc/games.php?game=61
* Fixed warning in `script_exists` by casting the script id to size_t so it can be safely compared with `enigma::script_idmax`.
* Fixed warnings in `room_next`, …

Cleanup Universal System Warnings

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSjoystick.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSsystem.cpp

More warnings cleanup, this time for Windows. Very obvious, `joystick_load` was using a lot more boilerplate than it needed to just to return whether it was successful. Apparently GCC also doesn't like passing `NULL` as an argument to non-pointer parameters which was giving a warning in `os_is_network_connected()`.

Cleanup Win32 Warnings

---

ENIGMAsystem/SHELL/Platforms/SDL/Joystick.cpp

Very obvious, it seems @time-killer-games just made a small typo in SDL's `joystick_axis` when he did #1477. This was creating a warning because the `numb` parameter was unused and `axis` was being used uninitialized.

Cleanup SDL Warnings & Joystick Whitespace

---

ENIGMAsystem/SHELL/Widget_Systems/Win32/gtklike.h
ENIGMAsystem/SHELL/Widget_Systems/Win32/widgets.cpp

Here we go cleaning up the Win32 widget system's warnings. First, Josh's `gtklike.h` widgets were using misleading indentation (two if conditions on the same line with no braces). Second, `WINVER` was being redefined since the change where we added `get_window_handle()` so I just moved the definition to the top of the file before all `windows.h` includes.

Cleanup Windows Widgets Warnings

---

CompilerSource/compiler/components/write_object_data.cpp
ENIGMAsystem/SHELL/Universal_System/instance_system.cpp
ENIGMAsystem/SHELL/Universal_System/object.cpp

I chose to keep this out of #1596 because this cleanup was a wee bit more involved and I didn't want to lose sight of why these warnings are being fixed. So basically we had `obj_idmax` in `IDE_EDIT_objectdeclarations.h` which was a duplicate of `object_idmax` in `IDE_EDIT_resourcenames.h`. This was creating confusion in our code because `obj_idmax` was `int` and `object_idmax` is `size_t` like the rest of the `*_idmax` resource globals. Git blame tells me that in 542bf10014a9068e23006dc4872a053e126b59c2 it was polygonz who added this duplication.
* Removed `obj_idmax` which is a duplicate of `object_idmax` so the compiler doesn't write it anymore.
* Cast an instance id in `fetch_instance_by_int` to `size_t` in order to safely compare it with `object_idmax`.
* Changed references of …

Cleanup Object Warnings

---

CommandLine/testing/SimpleTests/string_test.sog/create.edl
ENIGMAsystem/SHELL/Platforms/General/PFmain.h
ENIGMAsystem/SHELL/Platforms/General/POSIX/Utility.cpp
ENIGMAsystem/SHELL/Universal_System/estring.cpp
ENIGMAsystem/SHELL/Universal_System/estring.h

These two methods are useful in tandem. The former runs a shell function and returns all data it printed as a string. The latter splits a string on a given delimiter (common to many languages).
An example usage is performing an ls, as follows (note that no sane program should do this instead of using the `file_find` API):
```cpp
files = string_split(execute_shell_for_output("ls"), "#", true);
for (int i = 0; i < array_length_1d(files); ++i) {
show_message(">> " + files[i]);
}
```

Implement `execute_shell_for_output` and `string_split`.

---

CommandLine/libEGM/action.h
CompilerSource/compiler/components/write_defragged_events.cpp
shared/protos/Action.proto
shared/protos/Object.proto
shared/protos/Timeline.proto

I don't know how I missed this in #1555. If you build the current master you'll see a warning about `Timeline.proto` importing `Event.proto` but not using it. That is vestigial from before #1555 was merged. `Timeline.proto` has its own Moment message now. I moved the Event message to `Object.proto` where it needs to be and then renamed `Event.proto` to `Action.proto` since it no longer has anything to do with events.

Cleanup Event Proto & Rename to Action Proto

---

ENIGMAsystem/SHELL/Universal_System/Extensions/ttf/ttf.cpp

The FreeType extension should be rendering fonts at 96 dpi, which is what GameMaker has always rendered fonts at and continues to this day. The 96 dpi comes from the fact that this has been the default Windows dpi setting since the 1980s, though it's 72 dpi for Apple/Mac. I am splitting this out from #1288 so it isn't forgotten. The same change has already been made for LateralGM.
https://github.com/enigma-dev/lgmplugin/pull/65

Fix FreeType Extension DPI

---

ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.h
ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.m

**New Functions Added:**
- show_message_cancelable(str) same as show_message() but has a cancel button.
- show_question_cancelable(str) same as show_question() but has a cancel button.
- show_attempt(str) shows a special type of error message, that unlike show_error(), it does not provide a way to abort the application. Instead, it has a 'Retry' and a 'Cancel' button.
- message_get_caption() returns a custom message caption that was previously set by the developer, if one was set. Otherwise, it will return an empty string.
- message_set_caption(str) sets a custom message caption for the message, question, attempt, error, and input, and hidden input dialogs. Set str to an empty string to restore the default value, which is either the game window title or "Error" depending on the dialog …

Add new functions to Cocoa Widgets

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp

In some different places I use the swap chain to get the presentation parameters to tweak them before doing a display reset to change them. This is just me creating a helper to assist with that and make it a little cleaner.

Cleanup Direct3D9 Swap Chain

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp

This one is pretty obvious, I am switching from `MessageBox` to `show_error` so that I can force the game closed whenever a display reset is not successful in the Direct3D9 bridge. It's important to do this because this is not a scenario in which we can continue running the game. It does not matter if the display reset is caused by us or the result of a lost device. I tested to ensure this does what I think. I put myself in the managed Direct3D9, commented out releasing of the surfaces on lost device, and noticed the `MessageBox` version segfaults after showing the reset failed message. The new version shows our standard error dialog and then forces the game closed with `Game returned 0`. I also removed some unused headers and namespaces while I was in here.

Direct3D9 Fatal Display Reset

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D11.cpp
ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11shader.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/Direct3D11Headers.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DIRECTX9Std.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/Direct3D9Headers.h

This is just me removing a few more unused includes in the Direct3D systems and moving stuff where it needs to be. Specifically the `extern HWND hWnd;` declaration I moved out of `Direct3D9Headers.h` and over to the Direct3D9 bridge because none of D3D9 actually needs it and it's better to expose less rather than more when it comes to headers. Some of these unused headers were also causing misplaced dependencies, such as `<string>` which wasn't even needed by `Direct3D9Headers.h` just `DX11shader.h`.

Cleanup Direct3D Bridges

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp

This is a very simple oversight I made. When we reset the Direct3D9 device, we only need to restore our state cache if we are using the normal, managed Direct3D 9.0 device. A 9Ex device does not lose state information. So this pull request simply adds a condition to our Reset helper to only restore the state when using the managed device.
>Calling IDirect3DDevice9::Reset causes all texture memory surfaces to be lost, managed textures to be flushed from video memory, and all **state information** to be lost.
https://docs.microsoft.com/en-us/windows/desktop/api/d3d9/nf-d3d9-idirect3ddevice9-reset
>Unlike previous versions of DirectX, calling IDirect3DDevice9Ex::ResetEx **does not cause** surfaces, textures or **state information** to be lost. …

Direct3D9 State Reset

---

ENIGMAsystem/SHELL/Universal_System/debugscope.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp

I am proposing this change to make debug error dialogs a little nicer to read. I am taking some inspiration from Python and Java stack trace formatting.
* Return a special debug stack message when the debug stack is empty.
* Indent the frames of the stack trace by two spaces.
* Append a newline at the end of a stack frame instead of prepending it to the beginning.
* Add a blank line between the debug error message and the debug stack message.

Error Dialog Debug Stack Formatting

---

shared/eyaml/eyaml.cpp
shared/eyaml/eyaml.h

Seems as though MSVC doesn't know what RVO is, which shouldn't surprise anyone.

Forbid copying of ey_data

---

ENIGMAsystem/SHELL/Bridges/General/Win32-Direct3D9.cpp

I literally cannot stand the extra indentation within namespaces. That's all this change does, is reset the indentation level in namespace `enigma` to match other sources.

Format Win32-Direct3D9 Bridge

---

ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.m

Pressing the escape key would close the color picker dialog functions ok, but the game would remain in a frozen modal state. It only happened with pressing escape, and did not happen when pressing the ok or cancel buttons. This pr fixes that issue and treats the escape key as the cancel button by returning -1 like GM. Demo executable demonstrating this has been fixed can be downloaded here: [CocoaWidgets.zip](https://github.com/enigma-dev/enigma-dev/files/3101552/CocoaWidgets.zip)

[Cocoa] fix for get_color() on esc key

---

CompilerSource/compiler/compile.cpp
CompilerSource/compiler/jdi_utility.cpp
CompilerSource/languages/lang_CPP.cpp
CompilerSource/languages/lang_CPP.h
CompilerSource/languages/language_adapter.h
CompilerSource/parser/parser_components.cpp
CompilerSource/syntax/syntax.cpp
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32-OpenGL1/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32-OpenGL3/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/xlib-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/GTest/include.h
ENIGMAsystem/SHELL/Universal_System/var4.cpp
ENIGMAsystem/SHELL/Universal_System/var4.h

Types and global variable names will not be usable in EDL unless they are explicitly defined or used (via `using` directive) from the `enigma_user` namespace.
This removes conflicts with Bessel `y0`/`y1` functions and `time` as variable names.

Use only the contents of enigma_user for compilation.

---

ENIGMAsystem/SHELL/Universal_System/actions.h

They should have been in `enigma_user` namespace and that's why #1677 just broke Project Mario. With this change, Project Mario builds again. Since fundies is pressuring me for other stuff, I am not going to bother writing a CI test for this yet. However, I can very soon write us an object/instance inheritance test that's comprehensive.

Fix Scope of Event Functions

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GStextures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GStextures.h
ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.cpp
ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLtextures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3textures.cpp

I forgot to remove two texture state functions from the backends in #1636.

Remove Texture State Functions From Backends

---

CommandLine/testing/SimpleTests/math_test.sog/create.edl
ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
ENIGMAsystem/SHELL/Platforms/General/PFmain.h
ENIGMAsystem/SHELL/Platforms/General/POSIX/Utility.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp
ENIGMAsystem/SHELL/Universal_System/mathnc.h

I am trying to fix clamp and keep it that way by adding it to the math CI test. I first added it to the CI test to prove that it fails/is ambiguous since #1677 exposed namespace `enigma::` to the user's codegen headers. This specifically effects my "Modern Economy" city simulation game which uses clamp to keep the current simulated month in the range of 0-11.
I talked to Josh and he told me it's time to deduplicate the two clamps. He said it was ok to use the user function in the platforms, which is what I've done here. Platforms uses the clamp function in its timing functionality. This resolves the ambiguity, but it required that I allow including `mathnc.h` from engine source's (something we previously disallowed).
Going further, this doesn't actually solve the root problem here, which …

Fix Math Clamp

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSd3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSd3d.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLd3d.cpp

This fixes a regression to the fog color for Direct3D9 that was introduced in #1636.

Fix Direct3D9 Fog Color

---

ENIGMAsystem/SHELL/Bridges/Cocoa-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/SDL-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/xlib-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL/GLscreen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL/GLscreen.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL/Makefile
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLscreen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/Makefile
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/OPENGLStd.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/Makefile
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/OPENGL3Std.cpp

This has been an issue for a while. The MSAA `display_reset` does not work at all in OpenGL1 on master. The `display_reset` also just doesn't work at all on any platform except Windows because we had the code to create the MSAA fbo in the bridge. This pull request fixes all of that.
I moved the MSAA fbo handling out of the `Win32-OpenGL` bridge and into the `Graphics_System/OpenGL/` general OpenGL folder. I left the vsync control in the bridges since that is windowing system specific. Then I made the GL general `display_reset` call the backend vsync control helper then finally create the MSAA fbo. I included checks for whether fbo support is actually available so people like polygonz won't feel left out. I also decided to deduplicate the OpenGL makefiles while I was in here.
Edit: Also, I …

Fix OpenGL Multisampling FBO For Xlib/Non-WGL

---

ENIGMAsystem/SHELL/Universal_System/Extensions/Asynchronous/ASYNCdialog.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/include.h

I documented this pretty clearly already.
GMSv1.4: `ds_map_replace` inserts value at key, erasing old value at key if it exists
GM8.1: `ds_map_replace` if key is found, erases old value at key and inserts new value at key
This pull request does not actually fix the underlying compatibility issue, but #1461 would. What this pull request does is just rename `ds_map_replaceanyway` to `ds_map_overwrite` which is a name Josh gave me that I like better.

Rename DS Map Overwrite

---

CommandLine/testing/SimpleTests/data_structure_test.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp

Since I added a CI test for the data structure lists, I've been wanting to expand it to cover data structure maps as well. This made me more sad at GameMaker and YoYoGames.
First, the `ds_map_copy` function should have really been called assign, its name is a bit of a misnomer. As if that wasn't sad enough, YoYoGames have completely broken maps in GMSv1.4. In older GM8.1 and lower as well as ENIGMA, they are multimaps. In GMSv1.4 they are just normal maps and do not allow duplicate keys. This was confirmed by @rpjohnst over Discord where he did tell me he ran onto this independently while working on Dejavu.
Finally, while I was in here I did manage to notice that `ds_map_find_next` and `ds_map_find_previous` had a bug. They should have returned an undefined variant so the user can check …

Add DS Map Tests to CI

---

CommandLine/testing/SimpleTests/data_structure_test.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp

Friend of #1697, #1698, and #1699 expanding coverage of the CI to include data structure priority.
Like the changes I made for maps in #1697, I have changed the find functions of priority to return an undefined var when the value can't be found. I tested GMSv1.4 to make sure this is consistent, and it is. I find this to be sane and like the idea because the user is able to check the return value with `is_undefined` to see if something was found.
```cpp
var lol;
lol = ds_priority_create();
show_message(string(is_undefined(ds_priority_find_min(lol))));
show_message(string(is_undefined(ds_priority_find_max(lol))));
show_message(string(is_undefined(ds_priority_find_priority(lol, "ok"))));
```

Add DS Priority Tests To CI

---

CommandLine/testing/SimpleTests/data_structure_test.sog/create.edl

Friend of #1697, #1698,  #1699, and #1701 expanding coverage of the CI to include data structure grid.
This one was more of a royal pain than the others. I ran into a few issues along the way. I decided to leave out the disk functions here first because they are tricky to test and I believe I also ran into a bug with them. Also, I _fudged_ the numbers with regards to computation of the mean for now due to a compile error with gtest epsilon comparison ambiguity.
```
./Universal_System/Extensions/GTest/include.h: In instantiation of 'bool enigma::within_five_ulp(T, U) [with T = enigma_user::variant; U = double]':
./Universal_System/Extensions/GTest/include.h:94:43:   required from 'void enigma_user::gtest_check_eq_eps(T, U, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, …
```

Add DS Grid Tests To CI

---

CommandLine/testing/Tests/draw_test.sog/create.edl
CommandLine/testing/Tests/draw_test.sog/draw.edl
ENIGMAsystem/SHELL/Graphics_Systems/General/GSprimitives.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSprimitives.h
ENIGMAsystem/SHELL/Graphics_Systems/General/GSstdraw.cpp

The aim of this pull request is to fix a regression I caused in #1636. Basically, if the user submits their own vertex buffer, then anything that's currently in the draw batch needs to be flushed first in order for the depth to be correct. This has actually seriously regressed the D3D11 system, but none of the others believe it or not.
What I am doing first is expanding the draw test to submit a vertex buffer directly after drawing a black rectangle with the state **NOT** dirty in between. What should happen is the vertex buffer should appear on top, but when I test it locally, we get the rect on top of the vertex buffer contents. Once EnigmaBot confirms, I will then actually fix the flushing.
Also reverting 94eb31590716cad9ca36b24df10fe940e28dc91b where fundies broke the batch flush …

Draw Batch & Vertex Submit Mixing Fix

---

CommandLine/emake/Makefile
CompilerSource/Makefile
Makefile

This fixes what I discovered in #1230 and will hopefully make the Travis Mac jobs pass again. Using a comma is more portable than the equal sign (which is GNU Make specific).
Edit: Ok so it did fix it part way, now there's other issues addressed by #1294, but this is a good start.

Mac Travis Fix

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSscreen.cpp

This fixes #1712 for hugar. Basically, we just had a typo and were passing the xscale for both the xscale and the yscale of the room background.

Fix Room Background Y Scale

---

CommandLine/testing/SimpleTests/file_input_output.sog/create.edl
ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.cpp
ENIGMAsystem/SHELL/Universal_System/estring.cpp
ENIGMAsystem/SHELL/Universal_System/fileio.cpp

Adding a simple CI test to cover file input output for text and binary files. The strategy is to write out some test files on the spot and then verify what we read back in.
I fixed the `file_bin_rewrite` function to be more GM8.1 compatible. Now it will allow you to read bytes if you rewrite, write some bytes, seek, read the bytes just written. Basically the function changes the mode of the file to be read and write, regardless of what mode it was originally opened in. This is not GMSv1.4 compatible however, because they changed it to not do this.
I fixed `file_copy` in here for POSIX/Linux using code provided by Josh which uses standard streams to accomplish the task. It worked pretty good locally, even copying files that were 0 bytes in size. This had to be done because the old hack …

File I/O Tests

---

CommandLine/testing/SimpleTests/data_structure_test.sog/create.edl

I just noticed I missed all of the duplicate functions, which are ENIGMA specific, in my data structures test. I think they are useful, as are the copy versions, so I am proposing we cover them in the tests.

Data Structure Duplicate Tests

---

CommandLine/testing/SimpleTests/file_input_output.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/fileio.cpp
ENIGMAsystem/SHELL/Universal_System/fileio.h

This attempts to resolve #1136 for @time-killer-games by making `file_text_readln` return the contents of the line read as a string. This is in fact GMSv1.4 behavior, and I agree with it as it makes it more like the C#/Java functions. It's also a lot less verbose to read files with this. I expanded the file I/O test to cover this change in behavior as well.

File Text Read Line Return

---

CommandLine/testing/SimpleTests/data_structure_test.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp

This is a friend of #1716 expanding the data structures test to cover other misc functions I missed. Some are unique to ENIGMA and some are not. Regardless, I discovered them by actually looking at the code coverage's covered lines in the data structure source code.
I still am not testing grid disk functions yet because they are tricky. I am also not testing the read and write functions for each data structure because I originally thought they were unimplemented. Even though they are implemented, they too are complicated to test, so I am not bothering for now.
While I was in here I changed the `ds_list_delete` range overload to be inclusive of the last element. I did this because the condition seemed like that's what was originally intended. If somebody wants to dispute me, go ahead.

Miscellaneous Data Structure Tests

---

CommandLine/testing/SimpleTests/file_input_output.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/fileio.cpp
ENIGMAsystem/SHELL/Universal_System/fileio.h

This pull request is a friend of #1717 and does the same thing for writing. I want to provide a new overload for `file_text_writeln` that accepts a string. I used to always make a script for this in my GM games, and that includes Project Mario. I also expanded the file I/O test to cover the new write line overload.

File Text Write Line Overload

---

CommandLine/testing/Tests/draw_test.sog/create.edl
CommandLine/testing/Tests/draw_test.sog/draw.edl
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11draw.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/Direct3D11Headers.h
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9draw.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSscreen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.cpp
ENIGMAsystem/SHELL/Graphics_Systems/None/fillin.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL/GLtextures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLscreen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLstdraw.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3screen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3stdraw.cpp
ENIGMAsystem/SHELL/Graphics_Systems/graphics_mandatory.h

This pull request is a friend of #1722 and #1648. The idea behind this pull request is that the screen is a surface too. I have created here a new mandatory interface for reading the screen backbuffer to generically reimplement all of the screen transfer functions. There is only read provided, no write like textures, as I don't see the need.
```cpp
/// Retrieve image data from back buffer, in unsigned char, BGRA format.
/// Flipped parameter is optional, but backend must provide it when nonzero.
unsigned char* graphics_copy_screen_pixels(unsigned* fullwidth, unsigned* fullheight, bool* flipped=nullptr);
unsigned char* graphics_copy_screen_pixels(int x, int y, int width, int height, bool* flipped=nullptr);
```
This pull request actually fixes a crash on exit in @time-killer-games Key to …

Generic Screen Transfer

---

CommandLine/emake/EnigmaCallbacks.hpp
shared/protos/Makefile
shared/protos/compiler.proto
shared/protos/server.proto

This pull request attempts to address issues like #1723 which stem from #1292. Old protocol buffer's compiler can not even handle the RPC syntax. Since we aren't requiring GRPC yet in the default LGM/ENIGMA, we should not run protoc on the server proto.
What I've done here is readd my filter-out that fundies had removed in #1292. I also split the server RPC interface's compiler buffers out into a new `compiler.proto` file since emake does depend on that (just not the RPC stuff).
I tested locally myself to make clean with and without `CLI_ENABLE_SERVER=TRUE` defined. When it's not passed, `server.proto` is not passed to protoc at all, and no codegen is produced. However, emake does continue to work and `compiler.proto` is built. When server mode is enabled, then `server.proto` is passed to …

Disable Server Protobuf Fixes

---

ENIGMAsystem/SHELL/Universal_System/Extensions/libpng/libpng-ext.cpp

I ran onto this while working on #1725 and hugar also mentioned it to me and on the forums at the same time. The libpng extension was not respecting the flipped parameter when saving. The reason is because we were flipping both the source read and destination write indices, where one obviously undoes the other. We only need to flip one of the indexes, not both. The one we should flip is the destination write index, since it is bounded by height, where the source read index is bounded by fullheight.

Fix Flipped for libpng Extension Saving

---

CommandLine/testing/Tests/draw_blend_test.cpp
CommandLine/testing/Tests/draw_blend_test.sog/create.edl
CommandLine/testing/Tests/draw_blend_test.sog/draw.edl
ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.cpp

This is a recreation of #1518 which expands the continuous integration tests to include a test for the blend mode states. I am excluding from the blend matrix the enums which Travis's Mesa driver does not support.
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glBlendFunc.xml
This includes the following columns and rows which are excluded:
* `GL_SRC_COLOR` and `GL_ONE_MINUS_SRC_COLOR` for source
* `GL_DST_COLOR` and `GL_ONE_MINUS_DST_COLOR` for destination
* `GL_SRC_ALPHA_SATURATE` for destination

Blend States CI Test

---

Compilers/Windows/gcc.ey
ENIGMAsystem/SHELL/Platforms/Win32/Makefile

We had the workaround to find the FFI header for 64 bit, but didn't have it for 32 bit MinGW. We can actually just remove fundies previous hack and use pkg-config now. This addresses #1734.
NOTE: Special thanks to Sociopart!

Fix 32 bit MinGW FFI Include Directory

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/Makefile

MinGW's bundled `dxguid.lib` provides the old version 43 GUID. This replaces it with the header's copy by defining `INITGUID`, and selects the newest version by defining `D3D_COMPILER_VERSION` to 47.
This should be unnecessary when using the Windows SDK, but these macro definitions should be harmless in that case so I don't believe they need to be gated on the toolchain in use.

Use the version 47 IID_ID3D11ShaderReflection GUID for D3D11

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSfilemanip.cpp

For reference:
https://stackoverflow.com/questions/49620394/writeprivateprofilestring-works-in-main-but-not-in-function
"Also, if you read their documentation, you would see that you SHOULD NOT use a relative path for the INI file, or else the file will be relative to the Windows installation folder, not your app folder."
GetFullPathName fixes this issue because the whole purpose of that function is to automatically convert relative paths to absolute.

allow using relative paths for ini writing

---

CommandLine/emake/EnigmaCallbacks.hpp
CommandLine/emake/Makefile
CommandLine/emake/OptionsParser.hpp
CommandLine/libEGM/CMakeLists.txt
CommandLine/libEGM/Makefile
CompilerSource/Makefile
Makefile
shared/protos/CMakeLists.txt
shared/protos/Makefile

- Simplify the recursive $(MAKE) invocations to a single-layered dependency
graph.
- Move the generated .pb.cc files into .eobjs/.
- Don't emit a spurious error looking for gRPC without CLI_ENABLE_SERVER.

Refactor the libProtocols Makefile

---

CommandLine/testing/SimpleTests/file_input_output.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/estring.cpp

when there is a period in the path (and not and not in the file), it will return a non-empty string, when it should return an empty string.
This change fixes that issue.

fix filename_ext when period in path to file

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp
ENIGMAsystem/SHELL/Platforms/xlib/XLIBmain.cpp

This pull request fixes #1743 for Darkstar. Basically, we just needed to add a check if the `keyboard_string` was not empty before trying to remove a character from it. SDL did not have this problem as it seems it's already making that check. I am not bothering to add input tests right now, we can do that later. Let's just fix the crash for Darkstar right now. I confirm it fixed the crash for me and `keyboard_string` continues working just fine.

Fix Empty Keyboard String Crashes

---

CompilerSource/parser/collect_variables.cpp

This addresses #1746 and fixes building of TKG's Key to Success using emake (though there is still some emake bugs to work out that make the game buggy). It also allows me to proceed with the same action scoping fix to the LGM plugin.

Fix Declaration Parsing Loop

---

CommandLine/testing/SimpleTests/math_test.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/var_array.cpp
ENIGMAsystem/SHELL/Universal_System/var_array.h

This pull request adds a simple function called `array_set`, so that you can pass arrays into scripts and modify them there (without needing to return the array). I believe there's no way to do so from EDL directly, so I'm making this pull request.

Add array_set function

---

ENIGMAsystem/SHELL/Universal_System/random.cpp

I noticed in the logs that we have signed overflow in the random.
`Universal_System/random.cpp:138:47: runtime error: signed integer overflow: 236732942 * 134775813 cannot be represented in type 'int'`
It was triggered with the following seed:
`random_set_seed(236732942);`
This pull request uses casting and unsigned literals so that we use unsigned overflow which is allowed rather than undefined.

Fix Random Signed Overflow

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp
ENIGMAsystem/SHELL/Universal_System/roomsystem.h

So, I'm digging around trying to fix a crash in compile mode with regard to the caption. I started wondering, why do we have `current_caption` in user scope? Then I remembered that polygonz a couple of years ago (3359c9811602f2037d8691f1f1bd72da29423775) was trying to cache the window caption so that it wasn't redundantly changed since he claimed that was a performance bottleneck. The only variable GM ever had in user scope was `room_caption` and that's all we need too.
What I've done here is removed `current_caption` as a built-in global for the user and moved it to the Win32 source which still uses it. I decided not to get rid of it completely like the other platforms, because who knows if polygonz is actually correct about the bottleneck. I can say that I know `room_caption` is no …

Anonymize Cached Win32 Window Caption

---

ENIGMAsystem/SHELL/Platforms/xlib/LINUXjoystick.cpp

Got a crash here when trying to run an example. I think it detected something in my laptop as a joystick with axes but no buttons, which doesn't work with the existing init loop.

Fix OOB memory write and ioctl check in LINUXjoystick

---

ENIGMAsystem/SHELL/Universal_System/var4.h

When we moved exclusively to namespace `enigma_user`, we didn't move toString there, so the function is no longer allowed in EDL. Problem is, `string()` was a macro to it, so that was necessarily broken.
The best option for now is to remove the macro and use just the type in EDL. EDL will not force the std::string constructor to succeed on objects passed to the method, so GCC can silently fix it in the preprocessor for the time being.

Fix using string as type/function.

---

ENIGMAsystem/SHELL/Universal_System/Makefile

So, I know this has been driving us all nuts for a while. I decided to take a close look at the extension and build system today with Rusky and reason about the problem of not being able to disable the path extension.
The decision I made was to have the sources which use `PATH_EXT_SET` have `API_Switchboard.h` as a dependency. Because the switchboard is generated, whenever the path extension is enabled or disabled, the switchboard will change. That means the appropriate sources can know when they need to be recompiled. The only problem with this I see is that switchboard is generated indiscriminately, and it may cause these sources to always be recompiled.
Regardless, this does fix issues with enabling and disabling the path extension.

Path Extension Disabling Fix

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSfilemanip.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/IniFilesystem/Makefile
ENIGMAsystem/SHELL/Universal_System/Extensions/IniFilesystem/Win32Ini.cpp
appveyor.yml

I'm doing this so that on all platforms users will consistently be expected to enable the extension in order to use the INI functions.
Additionally, UTF-8 support is added.

Move Win32 INI Funcs to IniFileSystem Extension

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.h
ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXdirectory.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp

```
// win32
// converts a relative path to absolute if the path exists
string filename_absolute(string fname) {
if (file_exists(fname) || directory_exists(fname)) {
wchar_t rpath[MAX_PATH];
tstring tstr_fname = widen(fname);
GetFullPathNameW(tstr_fname.c_str(), MAX_PATH, rpath, NULL); 
return shorten(rpath);
} else { return ""; }
}
// deletes the environment variable if set to empty string
bool environment_set_variable(const string &name, const string &value) {
tstring tstr_name = widen(name);
tstring tstr_value = widen(value);
if (value == "") return (SetEnvironmentVariableW(tstr_name.c_str(), NULL) != 0);
return (SetEnvironmentVariableW(tstr_name.c_str(), tstr_value.c_str()) != 0);
}
```
```
// posix
// converts a relative path to absolute if the path exists
string …
```

Add functions environment_set_variable() and filename_absolute()

---

ENIGMAsystem/SHELL/Universal_System/Extensions/Asynchronous/ASYNCdialog.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/Asynchronous/ASYNCdialog.h
ENIGMAsystem/SHELL/Widget_Systems/General/WSdialogs.h
ENIGMAsystem/SHELL/Widget_Systems/None/nowidget_impl.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/resources.rc

This is a complete re-write of Windows Widgets that adds UTF-8 support to most of the functions as well as adds all the functions that were always a part of the other system that were missing in Win32 to be a part of Windows Widgets as well. You may test this with the following demo EXE and GM81 source files: [Win32.zip](https://github.com/enigma-dev/enigma-dev/files/3296744/Win32.zip)
As a side note, I changed the get_directory() function to have "Select Directory" as the titlebar caption and the "OK" button label to say "Select" to match what YoYo Games did with the exact same dialog in the IDE:
Robert complained last time I changed that dialog to do this and I'm just explaining my reasoning for this.

Make Windows Widgets Compatible w/ Other Platforms

---

ENIGMAsystem/SHELL/Universal_System/Extensions/IniFilesystem/About.ey

Sam moved the Win32 INI functions over to the extension in #1755, but did not enable that extension by default. This is annoying for any project using INI that isn't converted to EGM, and people aren't converting to EGM because it's busted at the moment. Let's go ahead and enable the INI extension by default now.
He also probably should have moved the `PFini.h` to the extension `include.h` now to enable games to fail fast if they use ini functions. That is better than making them wait till link time for the compile to fail.

Enable INI Extension by Default

---

ENIGMAsystem/SHELL/Widget_Systems/KDialog/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/Zenity/dialogs.cpp

makes win32 and zenity have the correct icons in the dialog and, in zenity's case, running in desktops using KDE, the title bar as well. OK/Cancel should have a question mark instead of "i" for information.
error happened with the default kdialog shipped with certain linux distro's (since disco dingo release), and not the one you would've installed from the now obsolete package kde-baseapps-bin. This fixes the issue.

[win32, zenity] fix dialog icons, [kdialog] fix error message in file dialogs

---

.gitignore
.travis.yml
CommandLine/emake/Main.cpp
CommandLine/testing/Platform/TestHarness-X11.cpp
CompilerSource/JDI/src/API/error_reporting.cpp
CompilerSource/backend/ideprint.cpp
CompilerSource/general/bettersystem.cpp
CompilerSource/main.cpp
ENIGMAsystem/SHELL/Makefile
Makefile
appveyor.yml
logs/.gitignore
share_logs.sh

redirects. cout/cerr to files for the compiler and lib egm unless the env var ENIGMA_DEBUG is set to true. Added script share_logs.sh for the users and the ci to upload more detailed logs. Also quiets the engines makefile.
TODO: the share_logs.sh scripts should be run by the testharness between test games

quiet enigmas printing

---

ENIGMAsystem/SHELL/auxilary.h

When updating the copyright headers in eed62d3fc9571f9aed45f2757acac0dafe026d00 in 2013, I made a mistake. I accidentally included myself on the SHELL auxiliary header which I never had anything to do with. Finally, the year shouldn't have been changed either.

Fix SHELL Auxiliary Copyright

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSsystem.cpp
ENIGMAsystem/SHELL/Audio_Systems/DirectSound/SoundResource.h
ENIGMAsystem/SHELL/Universal_System/Resources/AssetArray.h

After talking to Rusky I caught two problems in #1767.
First, it's not possible to move from a const rvalue reference and it just falls back to the copy constructor. So, I changed all the move methods of AssetArray to take a non-const rvalue reference.
>Beware of const! Const variables can not be moved from, since move constructors take a non-const (rvalue) reference. However the compiler will **silently fall-back to the copy constructor**. https://www.chromium.org/rvalue-references#TOC-8.-Move-constructors-will-only-bind-to-non-const-rvalues.
Second, the destructor I added for Sound actually causes a problem. Since we first allocate the Sound on the stack before we add it to the asset array, its destructor is called releasing the COM interface pointer for the DirectSound buffer. This …

AssetArray Move Fixes

---

ENIGMAsystem/SHELL/Universal_System/Extensions/Asynchronous/ASYNCdialog.cpp

At some point, I don't know when, the bottom half of the copyright header in the async extension got mutilated. This is just a small request to fix it.

Async Extension Copyright Fix

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel_impl.h

In an attempt to spread the new AssetArray storage around, I am proposing we switch the model class over. It's already generalized and pretty self-contained so it's a good spot. Previously the model class had no debug checking for ids, but it does now!
The class still has to use vector to store its component primitives though. If we recall back to #1289, we decided to stop returning an id for the primitives. If we continued doing that we could have used AssetArray for the primitives. But since we now allow the model to combine adjacent primitives among other heuristics, it's not efficient to allow the user to manage individual primitives manually. That's ok because it was never a GM feature anyway.

AssetArray for Graphics Model

---

ENIGMAsystem/SHELL/Universal_System/Extensions/VirtualKeys/virtualkeys.cpp
ENIGMAsystem/SHELL/Universal_System/Resources/AssetArray.h

This pull request attempts to implement what I described in #1807 as an essential feature of the AssetArray. It should be possible to iterate over only the existing assets in the array. For this, I am providing a custom exists iterator for AssetArray that works in range-based for loops.
In collusion with @rpjohnst we settled on an API where the iterator dereferences to a pair, allowing you to access the id of the resource. This was particularly needed in the Virtual Keys extension so the id of a virtual key could be passed to one of the virtual key functions. DirectSound will require it for similar reasons too, and the id is just something you generally want to know about when working with an asset.
I have _not_ implemented a skip list or segment tree because at this point we don't think …

Asset Exists Iterator

---

ENIGMAsystem/SHELL/Universal_System/Resources/AssetArray.h

Well, there was a critical mistake in #1814 that's causing games not to build on master. The logic I am applying here to fix it is that it's illegal to advance past the end iterator. In this case, when we have an empty AssetArray, like Virtual Keys extension is at startup, our begin was advancing to 1 and our end was at 0 so they could never be equal making for loops never terminate. Since we always unconditionally advance by at least 1, I decided we should just always start begin at -1 to fix this.

Empty Asset Array Iterator Fix

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSbasic.cpp

It seems the DirectSound functions that loop over all the existing sounds have had some issues for a while. Before AssetArray was introduced in #1767, they used a macro which actually caused them to abort on the first deleted sound. That was not correct at all as calling these functions should not be fatal. Now that #1814 gave us an exists iterator, we can use it to implement these functions correctly by looping over only the existing sound assets.
Here's a simple example that reproduces it on master. Just put the code in the create, create and load two sound resources, put the object in a room, and run.
```cpp
sound_play(snd_0);
sound_play(snd_1);
sound_delete(snd_1);
sound_stop_all();
```

DirectSound Asset Exists False Positive Fix

---

CI/solve_engine_deps.sh

We were missing lcov because of #1792 apparently so this should fix #1810 and bring back coverage reports.

Fix New CI Test Harness Coverage

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSstdraw.cpp

(Left is master; right is this pull request)
I've been complaining about `draw_button` being screwed up on master and decided to investigate. I found that originally when I started Direct3D9 I had made some fixes to the `draw_button` I added there in 9a48e644000e2837842bbda68f2ce6e805e79e14, but not to the original one. The original one had some flaws too apparently but ultimately my fix made it worse. Then what happened was we deduplicated these functions to general in 03290669f7da08f8227481dce002af4bebff1c89 and I picked the Direct3D9 one.
Now I am sitting down, again, and making sure it's actually correct. I have fixed the winding order and added comments to easily discern which primitive is which side of the button.

Draw Button Winding Order

---

CompilerSource/parser/parser_components.cpp

This fixes the regression mentioned in #1795 where locals are not being picked up inside constructors. Simple solution is to also look for the opening parenthesis of a type cast on the right side of the type, and treat the constructor as a cast. Then locals will be correctly prefixed with `ambi.` or `self.` for subsequent parsing and compiling stages. This fixes both SONIGMA and Wild Racing.
Caveat: C-style function pointers will temporarily regress as a result of this.

Fix Parser Reinterpret Type Cast

---

CommandLine/testing/SimpleTests/string_test.sog/create.edl

I realized that #1795 actually occurred in regular objects too and not just scripts. Since we patched it with #1820, I decided I want to add a test that will keep it from coming back. I have updated the CI strings test to validate the logical equality of the string constructor.
Edit: Apparently this doesn't actually test the thing we just fixed. It's only reproducible by passing an uninitialized var to the string constructor, which I don't want to do since that will error the test.
For now this can still be tested but what we could use later is an error suppression mechanism. Then we'd be able to test the actual thing we fixed.

String Constructor Logical Equality Test

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp

This pull request fixes #1823 and allows mouse release to be correctly detected outside the window. My testing indicates this is exactly what GM8.1 and GMSv1.4 do when receiving mouse down events. They capture the mouse until receiving a mouse release event.
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setcapture
It seems there may be a minor anomaly yet though. While this is better, it's not perfect. Sometimes we don't detect a mouse down when switching to an ENIGMA game, while GM _always_ does. Perhaps this is a timing difference between ENIGMA and GM.

Win32 Mouse Capture

---

ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp

This pull request is a friend of #1824 that attempts to fix #1823 for the SDL platform. While this pull request improves the compatibility, there is still a difference in behavior from GMSv1.4 and GM8.1. That is that a mouse button press is not detected when switching focus from another Window to an ENIGMA game. That's not a regression, because it's not recognized on master either. So, I wonder what else it is that we are doing differently.
https://wiki.libsdl.org/SDL_CaptureMouse
I tried capturing also in mouse enter/leave and window focus gain/lost events, but that didn't seem to help. So, this is just like the other pull request, while it's better, it's still not perfect.

SDL Mouse Capture

---

ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp

This one is for hugar, since he would like to use this function. The bug was just a very simple mistake in this mouse function. As we can see, all of the other mouse functions offset the button index by one, because 0 is `mb_none` in ENIGMA and GM.
This does not appear to have been a regression, the blame tells me the function has always been bugged.
https://github.com/enigma-dev/enigma-dev/blame/34455a78bcbd5f5377472564785b69248361aeec/ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp#L1008
I made a little test too. On this pr and GM8.1, my test means holding right down will prevent left showing a message. On ENIGMA master it doesn't stop the message from showing.
```cpp
if (mouse_check_button(mb_right))
mouse_clear(mb_left);
if (mouse_check_button(mb_left))
show_message("hello ding …
```

Mouse Clear Fix

---

ENIGMAsystem/SHELL/Universal_System/Extensions/ttf/Makefile
ENIGMAsystem/SHELL/Universal_System/Extensions/ttf/include.h
ENIGMAsystem/SHELL/Universal_System/Extensions/ttf/ttf.cpp

Just a few fixes pointed out to me by @time-killer-games which are necessary for me to even be able to use the extension now. We want to link FreeType statically to the game. We also want the `font_add` function signature declaration and definition to match.

FreeType2 Extension Static Linking

---

ENIGMAsystem/SHELL/Universal_System/Extensions/VirtualKeys/virtualkeys.cpp

This is a minor tweak to make the virtual keys behave more GMS like. In ENIGMA master, when you hold the left button and move off the virtual key, the keyboard event is still getting fired, even though the button no longer looks pressed. This is not the way GMSv1.4 behaves.
I applied De Morgan's law to my predicate logic in order to make ours behave the way GMSv1.4 does. That means that the virtual key does not need updated when the mouse is outside its rectangle or the left mouse button isn't down. When the virtual key doesn't need updated, it's possible to handle its release behavior, making the key no longer look pressed as well as firing a release event for its associated keycode. If the virtual key does need updated, then it's also being pressed, as it means the mouse is both inside …

Virtual Keys Pressed/Released Tweak

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
ENIGMAsystem/SHELL/Platforms/General/PFmain.h
ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/GTest/GTest.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/GTest/Makefile

This pull request addresses #1720 so that while gtest expect calls will not abort, they may fail the test when the game ends.
The first thing I had to do was get rid of the default parameter on `game_end` so that extensions are able to manipulate the game end return value. This circumvents having to update all of the existing tests to ask the gtest extension for an exit code to return or whether there was a failure. It may still be useful to provide that information later though.
I also had to tweak the Win32 and SDL platform's quit to just end the game rather than setting the exit code to 0, since that would preclude an extension being able to effect the game return code.
I tweaked the GTest Makefile in this too because I am tired of having to tweak it every time I want to run the …

Fix GTest Expect Exit Code Return

---

CI/build_and_run_game.sh

This pull request fixes the draw test regression caused by fundies in #1792 when he got rid of the screen size parameter for xvfb. Changing the screen size caused the `draw_getpixel` coordinates to be off and not return the correct value leading the expects to fail. The fact that the expects did not fail the overall test is an ongoing issue which #1844 covers.
The commit by me prior to fundies does not contain any failures:
https://travis-ci.org/enigma-dev/enigma-dev/jobs/557674696
His commit and every master commit since contains the same failures:
https://travis-ci.org/enigma-dev/enigma-dev/jobs/558269419#L1812
```
1812 EDL:1: Failure
1813 Failed
1814 Failure: Not true that draw_getpixel(surf_dupx + 2, surf_dupy + 2) (which is 16761666) is equal to c_red (which is 255).
1815 EDL:1: …
```

Fix Screen Reading Test

---

CI/build_and_run_game.sh
CommandLine/testing/Platform/TestHarness-X11.cpp
CommandLine/testing/TestHarness.hpp
CommandLine/testing/Tests/draw_3d_shapes_test.cpp
CommandLine/testing/Tests/draw_blend_test.cpp
CommandLine/testing/Tests/draw_test.cpp
CommandLine/testing/Tests/draw_tiles_test.cpp
CommandLine/testing/Tests/room_transition_test.cpp
CommandLine/testing/Tests/window_test.cpp

This pull request addresses #1844 by having the regular CI tests assert the game's return code.
It seems to have worked, as I tested bringing back fundies regression I fixed yesterday, and it caused the test harness job to fail.
https://travis-ci.org/enigma-dev/enigma-dev/jobs/567212206#L1767
Sometime soon we should look at deduplicating these cpp files as they have quite a bit of redundancy.

Test Harness Game Return

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
ENIGMAsystem/SHELL/Platforms/General/PFmain.h
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
ENIGMAsystem/SHELL/Platforms/platforms_mandatory.h
ENIGMAsystem/SHELL/Platforms/xlib/XLIBmain.cpp
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.h
ENIGMAsystem/SHELL/Universal_System/Resources/loading.cpp
ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp

Fixes the window_set_sizeable() to actually work, and the GML functions added since GMS 1.x - window_set_min/max_width()/height(). https://docs.yoyogames.com/source/dadiospice/002_reference/windows%20and%20views/the%20game%20window/window_set_max_width.html
Edit: this also fixes fullscreen and resizeable window bugs with the graphics not rendering scaled to the window size. All of that is no longer an issue! What can I say other than, "you're welcome!"
Edit2: Also fixed a bug with Win32 when trying to maximize the window, scaling is now handled correctly here, not just in xlib.
Edit3: also fixes get/set fullscreen switching. Global Game Settings for setting fullscreen, borderless mode, and resizeable window on both Win32 and XLib. You can now use dialogs in fullscreen with all graphics …

[XLib] Add Setting Window Min/Max, Fix Sizeable [Win32] Fix Maximize

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp

yes, bignono. you can't minimize the game via alt+tab if both fullscreen and stayontop.

FullScreen + StayOnTop = BigNoNo

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp

I also intend to rewrite fileio.cpp for Win32 that doesn't use POSIX API calls and supports UTF-8, in a different pr.
`show_message(execute_shell_for_output('cmd /c dir c:\'));`

Kill POSIX crap in Win32 execute_shell_for_output

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp

previously, execute_program would crash if you dragged the window by the title bar or clicked the close button over and over while a program is running with the wait argument true, and the game would also crash with execute_shell_for_output whenever trying to close a NULL handle, due to trying to run a nonexistent file or invalid command. This stuff is now fixed and no longer an issue,

fix segfaults with with execute_* functions

---

ENIGMAsystem/SHELL/Universal_System/image_formats.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.h

The old bitmap reader was difficult to reuse or extend. This new approach trades the single-copy reader approach for the ability to pass in arbitrary blocks of memory to decode. We could technically accomplish the same thing by just using a stringstream under the hood, but I'm not in the mood.
Also plugs in actual bitmap headers instead of trying to do everything in terms of hard-coded offsets in the file. This is in the interest of extending the reader with support for compression schemes (eg, RLE).

Bitmap reader rennovation.

---

ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/xlib/kdialog.cpp
ENIGMAsystem/SHELL/Widget_Systems/xlib/zenity.cpp

fixes cases where show_error() doesn't abort/exit when it should.

fix show_error()

---

CommandLine/testing/SmallTests.cpp

Enables the same set of default extensions (+GTest) in simple tests as in lgm

Match LGM's default Extensions in CI

---

CI/build_and_run_game.sh
CI/install_emake_deps.sh
CI/solve_engine_deps.sh
CI/split_jobs.sh
CommandLine/emake/EnigmaPlugin.cpp
CommandLine/emake/Main.cpp
CommandLine/emake/Makefile
CommandLine/emake/OptionsParser.cpp
CommandLine/emake/SOG.cpp
CommandLine/gm2egm/main.cpp
CommandLine/libEGM/Makefile
CommandLine/libEGM/filesystem.cpp
CommandLine/libEGM/filesystem.h
CommandLine/testing/Makefile
CommandLine/testing/SmallTests.cpp
CompilerSource/filesystem/file_find.cpp
CompilerSource/frontend.cpp
CompilerSource/gcc_interface/gcc_backend.cpp
CompilerSource/general/bettersystem.cpp
CompilerSource/languages/lang_CPP.cpp
CompilerSource/main.cpp
CompilerSource/makedir.cpp
Config.mk
ci-regression.sh
shared/strings_util.h

This PR brings the CI up to c++17 but it comes with some good and bad
Good:
* Brings the ci up to gcc-9 and in turn c++17
* Removes our dep on boost filesystem
* Fixed small bug in regression script that caused it to fail when deps changed between commits
Bad:
* "windows.h" has a conflict with std::byte so anywhere it's included I had to wrap it in a macro to fix the conflict.
* Ubuntu's ppa for newest gcc don't have multilib gccs so I had to disable our 64->32bit builds but this is a very uncommon scenario.
* Our current JDI isn't c++17 compliant but only clang on osx seems to care and that job was already broken.
Note: emake still depends on boost options but that can be addressed in a separate PR

c++17 for the CI

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp

Just like our X11/Xlib implementation, this gets the x/y values for the primary monitor, except this time for Windows. More info here: https://docs.microsoft.com/en-us/windows/win32/gdi/multiple-monitor-system-metrics

[Win32] implement proper display_get_x/y() funcs

---

ENIGMAsystem/SHELL/Universal_System/Extensions/FileDropper/FileDropper.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/FileDropper/FileDropper.h

I had a user from the GMC complain the window doesn't keep focus after a DND operation, so yeah...
I really want to add a macOS version of this ENIGMA extension, as I have already written it, and verified it works in an empty Xcode project, but it will have to wait until my icon pr gets merged because it relies on those changes, (more specifically the window_handle-related stuff in that pr)...
rip

[FileDropper] Keep Window Focus After File Dropped

---

CommandLine/emake/EnigmaPlugin.cpp
CommandLine/emake/EnigmaPlugin.hpp
CommandLine/emake/Main.cpp
CommandLine/emake/Server.cpp

These small changes here fix the crashes related to #1900 that I reported. With these changes RGM can now successfully compile multiple times in a row. It was simple minor mistakes I made when initially building the server and trying to get these different APIs glued together. What was going on basically was since the compile RPC takes a game (and not a project), I was making a temp project and moving ownership of the game to it. After the first compile, the game was getting destroyed by the project after return. Then the GRPC server came in and tried to delete the game, but it was already gone, hence segfault.
While I was in here Josh threatened me to accept const references instead. Also fundies forgot to remove boost from the server in #1894 so I had to do that too.

Fix GRPC Server Compile Game Crashes

---

ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp

Fix SDL Without Breaking Eveything Else

---

Default.mk

Fix fundies typo (9eefc9a850162617781cf86c2575a09f9fca68ad) on proto rules and restore the comment Rusky (eabb1b474d5abf7e2d58ae3eccf4ba875208a9c9) originally added there. This is an odd typo for fundies to make considering he copied everything else verbatim, but regardless this fixes #1901 and emake is successfully built the first time now.

Fix Default Proto Makefile Rules

---

Default.mk

I forgot the underscores on OBJDIR in #1905, can we just force amend the tip of master real fast? Also fundies forgot an underscore that's related to this underscore.
**Note:** It's still OBJDIR all through the SHELL makefiles too, but I guess it's ok for now since they are unrelated. Just hope it doesn't confuse people.

Add forgotten underscores

---

ENIGMAsystem/SHELL/Platforms/SDL/Icon.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Icon.h
ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSicon.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSicon.h
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
ENIGMAsystem/SHELL/Platforms/xlib/Makefile
ENIGMAsystem/SHELL/Platforms/xlib/XLIBicon.cpp
ENIGMAsystem/SHELL/Platforms/xlib/XLIBicon.h
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp
ENIGMAsystem/SHELL/Universal_System/Resources/sprites_internal.h
ENIGMAsystem/SHELL/Universal_System/Resources/spritestruct.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.h
ENIGMAsystem/SHELL/Widget_Systems/xlib/Makefile

Well, for the first time in the roughly 10 years the ENIGMA game engine has been around, you can now natively set a PNG icon for your game that will show in the title bar, task manager, system monitor, and Alt+Tab process swapper. No thanks to those fat lards Josh, Robert, and fundies. No offense, I love you guys, but I couldn't take it any longer so I decided to step in and add Linux icon support. The Win32 and SDL equivalents have also been added in this pr.
Includes the following functions:
- window_get_icon_index() returns the sprite index of the current icon
- window_get_icon_subimg() returns the sprite subimg of the current icon
- void window_set_icon(ind, subimg) sets the icon to use for the game from the given sprite resource
As a very small secondary change, I set up a more …

[Win32, X11, SDL] Set Window Icon from Sprite at Runtime

---

ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp

this is to prevent it from returning a valid sprite index when no sprite window icon was previously set

Init window_get_icon_index() as -1

---

CI/build_and_run_game.sh
CommandLine/emake/Main.cpp
CompilerSource/backend/ideprint.cpp
CompilerSource/main.cpp
Makefile
logs/.gitignore
share_logs.sh

Note: This brings back a lot of garbage printing during parse that should probably be manually hidden as it makes no sense to anyone but josh

fixes emake output for "--list" & "--sever" and moves log files to /tmp

---

ENIGMAsystem/SHELL/Platforms/xlib/XLIBicon.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.h

XLib icon changing requires prepending the size (width, height) of the bitmap to the color grid image data as the first two values of the array. In most other cases, converting the colors of a bitmap will not want this information to be a part of that array, so I made an optional argument of a boolean to prepend the size to the dynamic array while keeping the default value for it to be `false`. This will help in the future to those who may need re-usability of that function to suit their needs more properly.

[BGRA->ARGB] allow making prepending size optional relative to use case

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSsystem.cpp
ENIGMAsystem/SHELL/Bridges/Win32-Direct3D11/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32-Direct3D9/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32-OpenGL/graphics_bridge.cpp
ENIGMAsystem/SHELL/Bridges/Win32/WINDOWShandle.h
ENIGMAsystem/SHELL/Platforms/General/PFwindow.h
ENIGMAsystem/SHELL/Platforms/SDL/Android/Window.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Cocoa/Window.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Win32/Window.cpp
ENIGMAsystem/SHELL/Platforms/SDL/xlib/Window.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSjoystick.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.h
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
ENIGMAsystem/SHELL/Platforms/platforms_mandatory.h
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/DirectShow/DSvideo.cpp
ENIGMAsystem/SHELL/Universal_System/Extensions/FileDropper/FileDropper.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/widgets.cpp

This gives extensions (i.e. *.dll, *.dylib, *.so, etc.) and shell scripts (i.e. execute_shell_for_output, execute_shell, execute_program, etc.) access to window handle on all platforms except Android. Android threw errors for unknown types being used for the android window and surface, which is odd because I'm using the exact types specified by SDL docs; i guess i need to include a proper header but I don't know what that is and I've already tried the header I thought i needed but it didn't work out. so anyway, I commented out android's window handle code as a placeholder file for whenever we do add it correctly. As for the other platforms, this pr also makes the window handle more universal, expecting to use the same variable names for the window handle, and related platform-specific …

[All Platforms] Rework Window Handle

---

ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp

ok, so my last fix wasn't so great. I wanted to keep the client area of the window to not change position on screen when toggling the border, and since every window manager handles this differently, i decided to just revert this back to how it originally was, and forget about that all together.

fix borderless toggle (again)

---

CommandLine/testing/GitHub-ImageDiff.sh
CommandLine/testing/Tests/draw_test.sog/draw.edl

Use the workaround for authorization token in the header recommended by GitHub.
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

EnigmaBot Authorization

---

ENIGMAsystem/SHELL/Platforms/General/POSIX/shell.cpp

the fname argument needs quotes around it to accept spaces and it also needs a space between that and the args argument so the fname and first argument aren't fused together like Frankenstein's monster. Whoever wrote these functions initially was on crack. At least now, it works how it's supposed to, like it does on Windows, thanks to me. I can't believe this has been broken for the 10+ years ENIGMA has been around lol

[POSIX shell] these functions were written by a dummy

---

ENIGMAsystem/SHELL/Platforms/General/PFwindow.h
ENIGMAsystem/SHELL/Platforms/SDL/Android/Window.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Cocoa/Window.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Win32/Window.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Window.h
ENIGMAsystem/SHELL/Platforms/SDL/xlib/Window.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
ENIGMAsystem/SHELL/Platforms/platforms_mandatory.h
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp

Allows there to be some differentiation between a window id and a std::string that is not a window id.
Additonally, for clarification, I renamed window_id_init() to window_init() because it initializes all window related constants to be retrieved natively from SDL's window, not just the window id number by itself.

add typedef for window identifiers

---

CommandLine/testing/SimpleTests/file_input_output.sog/create.edl

Ensure file I/O test cleans up all files created. The test uses expects, not asserts, so it's unlikely that the test will exit before deleting the files unless there's an obscure error. I did this because fundies filed #1950 against the test.

File I/O Test Cleanup

---

ENIGMAsystem/SHELL/Universal_System/Resources/spriteinit.cpp

fundies made a small goof in #1937 and initialized all the sprites with contiguous ids instead of their actual ids. This broke a few games, including 1945 reported in #1976.

Fix Sprite Ids

---

ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp

Swaps sdl's default fullscreen mode to borderless window to match win32/xlib. Scaling is still bugged in true full screen.
workaround for #1980

swap sdl full screen modes

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSexternals.cpp

As I explained on #1972, which this pull request fixes, neither the `__cdecl` or `__stdcall` calling conventions are appropriate on 64 bit Windows. GML, even in the latest GMS2, is actually lacking in appropriate constants for the 64 bit calling conventions.

Fix Windows FFI

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSexternals.cpp

This was recommend by Josh as a fix for TKG's issue #1511 with passing strings to dlls. This cast allows the DLL to grab the pointer to the permanent string owned by the variant being cast. This should hypothetically fix the string corruption TKG was seeing because his dll will no longer be getting a pointer to a temporary string.

Fix DLL Strings

---

CI/asound.conf
CI/mirrorlist.mingw32
CI/mirrorlist.mingw64
CI/mirrorlist.msys
CI/split_jobs.sh
azure-pipelines.yml

Moves mingw cross compile jobs to azure / arch because mingw on ubuntu is too old for std::filesystem and I can't find a ppa to upgrade it

Move mingw cross jobs to azure / arch

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL-Common/shader.h

This adds the missing shader uniform array functions.
https://docs.yoyogames.com/source/dadiospice/002_reference/shaders/shader_set_uniform_f_array.html
https://docs.yoyogames.com/source/dadiospice/002_reference/shaders/shader_set_uniform_i_array.html
We already had them in our low-level GLSL API, but did not provide the GMS versions. This should resolve #1666 then. I also corrected a typo in the signature of these functions which 7a081caa7cd0cc0e78a040b86fd08a33a9043069 shows Harri did accidentally when he introduced them.

Shader Uniform Arrays Compatibility

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSshell.cpp

fixes a problem where execute_shell_for_output would hang the executed program whenever the output buffer exceeds 4096 characters.

Fix Execute Shell for Output Freeze

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSshell.cpp

This should hypothetically improve efficiency in `execute_program` when the wait parameter is true and a long-running process is executing. The problem with the old method was that it was only waking up every 5 milliseconds or when the process exited. This changes it to wake up when the process exits or when a message is received.

Execute Program Wait Optimization

---

ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp

Alright, I did it, I figured out how to fix #1828 correctly. Initial guesses that all mouse buttons need to be released for the mouse capture to be released are correct. The problem was I didn't want to call out to any other API, but then I realized all of the UP mouse input messages have a wParam which tells us the state of the other mouse buttons. Clearly it tells us whether all mouse buttons have been released!
With these changes the mouse capture works perfectly, the same as GMSv1.4, and other applications as it is expected to work. The mouse is correctly captured now and mouse releases are always properly detected inside and outside of the window.
What's funny is other people haven't figured out the wParam trick, and I notice several people using integers counters and other weird …

Fix Win32/SDL Mouse Capture Anomalies

---

ENIGMAsystem/SHELL/Platforms/General/PFfilemanip.h

Alternative to #2032 to resolve #1953.
One of the advantages to aliasing functions like this is it enables JDI to pickup the full signature of the function for syntax highlighting and auto completion. Unlike using a define, we won't later have to program JDI to fully pick up the signature of the function.

Add Directory Destroy Alias

---

ENIGMAsystem/SHELL/Universal_System/terminal_io.cpp
ENIGMAsystem/SHELL/Universal_System/terminal_io.h
ENIGMAsystem/SHELL/Widget_Systems/Cocoa/Makefile
ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/GTK+/Makefile
ENIGMAsystem/SHELL/Widget_Systems/GTK+/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/General/WSdialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/None/default_log.cpp
ENIGMAsystem/SHELL/Widget_Systems/Win32/Makefile
ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/xlib/Makefile
ENIGMAsystem/SHELL/Widget_Systems/xlib/kdialog.cpp
ENIGMAsystem/SHELL/Widget_Systems/xlib/zenity.cpp

This fixes #2034 to make `show_debug_message` usable again.
* Remove `show_debug_message` from the terminal I/O sources.
* Move common definition of function to `Widget_Systems/General/WSdialogs.cpp` for Win32, Cocoa, kdialog, & zenity.
* Flush stderr for the common version.
* Flush stdout for the None system implementation.

Show Debug Message Cleanup

---

ENIGMAsystem/SHELL/Widget_Systems/xlib/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/xlib/kdialog.cpp
ENIGMAsystem/SHELL/Widget_Systems/xlib/zenity.cpp

I made a goof in #2037 and accidentally broke KDialog/Zenity because I didn't realize in #1812 that tkg set up a dynamic engine to change dialog systems (something that could be accomplished if we just added hot loading to ENIGMA). What made things worse is that the Azure build was broke yesterday (but it's fixed today!) so I merged it without expecting it to pass.

Fix KDialog/Zenity Debug Message

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSsystem.cpp

This is a minor technicality that allows DirectSound to play sounds when the window is not focused, as OpenAL already behaves. Setting global focus on the secondary buffers is the only way to achieve this.
I tested and can confirm this is the way GM8.1 worked and it should be able to play looping sounds when not focused and regardless of whether the freeze on lose focus is ticked. GMSv1.4 with its legacy DirectSound system also behaved the same.
I am sure that `DSBCAPS_GLOBALFOCUS` is more correct than `DSBCAPS_STICKYFOCUS` from further testing. If the latter is used, and I open GM8.1 at the same time, switch focus to it causes ENIGMA to be muted. Only with `DSBCAPS_GLOBALFOCUS` is GM8.1 prevented from muting ENIGMA and vice versa. This was not the behavior with GMSv1.4 even though it …

DirectSound Global Focus

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp

There was a ton of vestigial junk in here that I got rid of and still made the same 100% logically equivalent. I see no reason to catch messages if we aren't using them and not let them get to the DefWindowProc, and I researched to make sure there wasn't a case that we were explicitly doing that.
I then promptly tested out some games including my own and tkg's usual Key to Success. I ran some benchmarks to check the framerate and stuff too and I didn't see any issues or regressions.

Cleanup Daft Window Procedure

---

ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp

THE STATE OF THE WINDOW SHOULD NOT BE MADE TO DEPEND UPON OTHER STATE OF THE WINDOW THAT IT DOES NOT ACTUALLY DEPEND UPON ITSELF

Fix Xlib Sizeable Crash

---

ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp

This stops it from crashing by giving it the scancode like it wants instead of the keycode. It does actually work now, except for CTRL, ALT, & Shift which will be fixed by #2058 later.
The documentation is clear that it expects scancodes, not keycodes, which do have different values.
https://wiki.libsdl.org/SDL_GetKeyboardState
Here's a test I devised that works in Win32 master but not SDL master, only this pull request.
```cpp
var text;
text = "";
text += string(keyboard_check_direct(vk_alt)) + " ";
text += string(keyboard_check_direct(vk_lalt)) + " ";
text += string(keyboard_check_direct(vk_ralt)) + "#";
text += string(keyboard_check_direct(vk_control)) + " ";
text += string(keyboard_check_direct(vk_lcontrol)) + " ";
text += string(keyboard_check_direct(vk_rcontrol)) + "#";
text += …
```

SDL Keyboard Direct Scancodes

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp

Lot of inefficient junk in here from when I (b6a1b612387ea9c1878b0ef2a2864fe2aef84035) originally added these. It looks like I must have copied them straight from the tutorial about setting the numlock but without actually bothering to pay too much attention because for some reason I thought the keystate was equivalent to its scancode, well it's _NOT_. There is no need at all for these functions to query the current state of the entire keyboard.
The next thing I did was use `MapVirtualKey` to obtain the correct scancode of the virtual key parameter for us to provide in the simulated keyboard event, even if most programs ignore it.
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeya
I appended `KEYEVENTF_EXTENDEDKEY` once I was sure of its meaning. …

Cleanup Win32 Keyboard Simulation

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp

So apparently I implemented (d08c3d9c6cab16827557f161d547be55e305357b) this way back and never tested it, then copied it to Linux where Josh later fixed it. Regardless, it doesn't work on master and it's also really slow because I didn't know how to write it and had it polling the keyboard state twice.
Anyway I made a little test to see if it was working and discovered that apparently the logical `vk_nokey` and `vk_anykey` were never supported by `keyboard_check_direct()`, not in GM8.1 or GMSv1.4 afaict.
```cpp
var text;
text = string(keyboard_check_direct(vk_nokey)) + " " + string(keyboard_check_direct(vk_anykey));
draw_text(0,0,text);
```
Now when I benchmark this with the #2059 test I had, it's still slower (100,000~ microseconds) than our SDL (5000~ microseconds) and GMSv1.4 (50,000~ …

Win32 Direct Keyboard State

---

CompilerSource/compiler/compile.cpp
CompilerSource/frontend.h
CompilerSource/general/bettersystem.cpp
CompilerSource/general/bettersystem.h
CompilerSource/main.cpp

This is the real alternative to #2067 allowing you to close the game, regardless of whether there's a dialog open or the game has hung. Obviously we've wanted a damn stop button for a very long time, but I didn't know how to do it before. This is very nice for if you accidentally press debug and you meant to hit run or etc, so you don't have to wait through a lengthy build process to fix your mistake.
The solution I came up with for right now is to add a new DLL method that sets a volatile `build_stopping` bool interpreted by `bettersystem` to indicate it should send a CTRL+C SIGINT signal to any child processes the ENIGMA build is waiting on. This means it can interrupt the make process or the game when it's being run.
I should mention that although ENIGMA's build is single threaded, the …

Damn Stop Button

---

.travis.yml
CompilerSource/general/bettersystem.cpp

Following up on #2068 to bring the game compile interrupt to Linux. This one was a little tricky for me because `waitpid` does not have an easy version that accepts a timeout and I was afraid sleeping would be a busy wait. I tried it on Linux myself and it seemed to work without high CPU usage, so I presume my concerns were unfounded. Regardless I opted to make it 10,000 microsecond sleep, or 10 milliseconds, or a hundreth of a second which is the same as the Win32 version I already merged.

POSIX Build Stopping

---

.github/ISSUE_TEMPLATE/config.yml

I tried to tell Josh he was going overboard making it markdown.

Fix Issue Config Website URL

---

CommandLine/libEGM/gmx.cpp
CompilerSource/compiler/compile.cpp
shared/protos/Timeline.proto
shared/strings_util.h

Yeah I tested it, of course I tested it. Timelines in GMX have a slightly different structure for moments than objects do for events. This means we need to support XML paths for the action nodes, which I've now added. First, I moved the `string_endswith` utility out of the compiler source and into the shared string utility header. I then have the GMX reader use that to check if the end of the GMX path name is "action" and in that case to handle the actions. It now looks for the first action child using the full path as well.
Also fyi, there's probably more tweaking to be done yet to the actions to code conversion because opening up a timeline in RGM right now looks like the following. The original version from the LGM plugin I believe does this in the codegen as well, but ideally the user …

Fix GMX Timeline Actions

---

CompilerSource/frontend.h
CompilerSource/general/bettersystem.cpp
CompilerSource/main.cpp

This addresses issues like #2073 which were caused by #2068 and #2070 when build stopping was added. The problem is that build stopping requires make/game to be run in a background process group, but that causes emake's own CTRL+C not to automatically be forwarded. I chose to do it Josh's way and just put it back the way it was and instead provide another method which enables the stop API so that the plugin can continue using it. This way, depending on our future requirements for emake, we can later reuse the functionality.
NOTE: I need additional feedback from fundies yet, I only guarded the creation of the process group for now. I need to know if redirecting STDIN was also a problem because as far as I am aware that's correct regardless of whether we create a process group or not and …

Stop API Enabling

---

CommandLine/testing/SimpleTests/buffers.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/buffers.h
ENIGMAsystem/SHELL/Universal_System/bufferstruct.cpp

* Added basic buffer CI test that covers the basic functions. Will need expanded later.
* Added missing `buffer_u64` and `buffer_text` types that were recently added with same GMSv1.4 enum int values.
* Added missing `buffer_exists` function. Can later be moved to AssetArray for cleanup.
* Tweaked buffer seek past end behavior to match GMSv1.4 for fixed and fast buffer types.
* Flattened the `buffer_sizeof` implementation and added the new types to it.

Buffers CI Test & Functionality

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
ENIGMAsystem/SHELL/Platforms/General/PFmain.h
ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp
ENIGMAsystem/SHELL/Platforms/General/PFwindow.h
ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp
ENIGMAsystem/SHELL/Platforms/xlib/XLIBmain.cpp

This follows from #2041 to immediately resolve #2119 for SDL by moving all of the keyboard state event processing and message handling logic to a general platform helper. Keyboard text handling is not included because in #2062 I am still working on that. In another pull request I can cleanup the mouse processing too. Then we can finally write an input regression test, which I have an idea to do using a stack and recording the states for several frames starting with a pressed and then checking expected values. That should hopefully enable me to get rid of most of the anomalous behavior that remains.

Generalize Keyboard Input Processing

---

shared/protos/Room.proto

This is just to kick off implementing GMS2-like, Tiled-inspired layers to the room protocol. I believe people desire an API like this and the use case is organizing instances by depth so they can be toggled together (e.g, activation & visibility) simultaneously. It also simplifies the editing experience to allow tiles and instances to coexist.
https://docs2.yoyogames.com/source/_build/3_scripting/4_gml_reference/rooms/layers/index.html
Eventually the repeated layers would completely replace tiles and instances, and libEGM would convert all GM projects to use a default layer for compatibility. For now, I just allow the layers to go unused. The next step would be implementing the API to the engine before libEGM and RGM are updated to reflect this.
* GMS2 deprecates backgrounds so I wasn't …

Room Layers Protocol Format

---

ENIGMAsystem/SHELL/Universal_System/Instances/instance.cpp

This is not a regression and has been this way for 8 years. In GMS where they finally added this function, the id parameter can mean an instance or an object, so I had to update the function. I changed it to use the instance iterators so that it can loop over all instances of a given object. It seems to work pretty good.
https://docs.yoyogames.com/source/dadiospice/002_reference/objects%20and%20instances/instances/instance%20functions/instance_destroy.html

Instance Destroy Objects

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9textures.cpp

This fixes a mistake in #2008 where fundies accidentally put the push pixels call before the texture was actually pushed into the asset array and the id was valid. Interestingly, I noticed another mistake in here by earlier me in that I was generating mipmaps before pushing the texture pixels too, though I don't know if that one matters since the driver creates them on demand when autogen mipmaps. Added some comments while I was in here too so somebody doesn't get the order mixed up again.

Fix Direct3D9 Texture Creation Crash

---

ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp

This is a small change that begins to fix the font rendering issues with subpixel alignment. I first changed Josh's rounding-to-zero (from fe4737f1cef66a1074490c5908ea2730674993bb) with regular round, so the code is clearer and because fonts never have negative dimensions anyway.
Then I removed his adding of a half pixel to the horizontal spacing of each glyph. The reason he didn't round here is because the xs member is a float, to allow fractional metrics and kerning. However, since he doesn't round, there's absolutely no point adding the half pixel. This immediately improves the font rendering under both OpenGL and Direct3D backends because the plugin has always been configured to draw fonts without fractional metrics. It seems that fractional font metrics were disabled by IsmAvatar …

Cleanup Font Metrics Initialization

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11d3d.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.h

The RAII of RawImage was causing a crash in D3D11 when lazy creating the default white texture. The simple solution here was to use a dynamically allocated 1x1 pixel array for the default white texture so it's not deleting stack-allocated memory. This white texture is necessary for the default shader or something, and I recall GMS doing the same thing based on my testing. If I recall correctly, this comes from ANGLE and has something to do with GLSL vs HLSL differences when sampling a texture that's not bound.
https://www.seas.upenn.edu/~pcozzi/OpenGLInsights/OpenGLInsights-ANGLE.pdf

Fix Direct3D11 White Texture Crash

---

ENIGMAsystem/SHELL/Universal_System/Resources/sprites.cpp

The default arguments aren't supposed to go in the source, they are already in the declaration of the header. This fixes the recompilation errors you get if you try to edit the source.

Fix Sprite Function Definition Signatures

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9textures.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/texture_atlas.cpp
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL-Common/textures.cpp
ENIGMAsystem/SHELL/Universal_System/Resources/backgrounds.cpp
ENIGMAsystem/SHELL/Universal_System/Resources/sprites.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.cpp
ENIGMAsystem/SHELL/Universal_System/nlpo2.h

Surfaces use the same texture creation routine as sprites/backgrounds so they can provide a texture id to the user for drawing onto user defined primitives. Surfaces don't need to be automatically resized to a power of two. Although it is recommended by the GM manual, it was never explicitly required except for HTML5.
>It is highly **_recommended_** that all surfaces be created with a size that is a power of 2, ie: 16, 128, 512 or 1024 pixels in size, for example. This is not exactly necessary on certain platforms (like Windows and MacOS) but it will certainly increase compatibility on those targets, while for HTML5 and devices it is essential and very it's important that you remember this or you may run into problems later.
https://docs.yoyogames.com/source/dadiospice/002_reference/surfac …

Fix Surfaces and Power of Two Typo

---

ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11d3d.cpp
ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11vertex.cpp

This fixes an issue with the state batching of the default Direct3D11 shader. We were indiscriminately uploading the matrices before, even if they weren't dirty, when submitting a vertex buffer. The other graphics systems upload them in the state flush, which is the correct way to do it. This makes the graphics a lot more stable, especially in 3D games, and objects don't randomly pop in and out of existence now.

Fix D3D11 FFP Shader State Batching

---

ENIGMAsystem/SHELL/Platforms/SDL/Gamepad.cpp

Addresses #2129 in support of user. We basically need a map of SDL button constants aligned to our own.
https://wiki.libsdl.org/SDL_GameControllerButton
I do the same thing in the XInput extension, except the map is inverted since my gamepad struct holds XInput state. I am not sure if honestly we could just make a generalized structure and reuse it in all of the places. I don't know what's better, converting to or from.
The SDL gamepads also need additional work yet such as threshold for other buttons and stuff.

Fix SDL Gamepad Button Mapping

---

CommandLine/testing/SimpleTests/file_input_output.sog/create.edl
ENIGMAsystem/SHELL/Universal_System/fileio.cpp

file_bin_read_byte skips over whitespace characters (08, 09, 0A, 0B, 0C, 0D, 0E and 20) unless the std::noskipws flag is used. Some gtests are added for this, to write then read back all byte values from 0-255

Fileio whitespace

---

CommandLine/testing/SimpleTests/file_input_output.sog/create.edl

Change function name 'directory_delete' to 'directory_destroy' at line 206, 
as discovered by gfundies and TKG

Update file IO command line test: Renamed function 'directory_delete'

---

ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Gamepad.cpp
ENIGMAsystem/SHELL/Platforms/SDL/Gamepad.h

This fixes #2091 in support of user. The problem is basically that the `cdevice->which` member is the device index (what GM uses) for device add events, but is actually the joystick instance id for button/axis/remove events. So clearly all we needed was a map of the joystick instance ids to the device indexes.
To clarify, you plug controller in, it has device index 0, and joystick instance id 0. You unplug it and plug it back in again, it still has device index 0, but then it has joystick instance id 1, and so on. It keeps getting incremented by one, because it's basically trying to track the player index, which we don't need because GM uses device index. Little test here you can do to make sure input still works after hot plugging.
```gml
draw_text(0,0,string(gamepad_is_connected(0))); …
```

Fix SDL Gamepad Hotplugging

---

ENIGMAsystem/SHELL/Platforms/SDL/Gamepad.cpp

This fixes a crash cleaning up gamepads at exit. You have to combine this with #2175 to get rid of the out of bounds issues. Then the issue remaining is just trying to close an already closed joystick if you already unplugged the joystick. All I had to do here was null the pointers and check if they are null like a good developer.

Fix SDL Gamepad Remove Crash

---

ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/include.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/include.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGLES2/include.h
ENIGMAsystem/SHELL/Graphics_Systems/OpenGLES3/include.h

This gives users access to glsl_ shader funcs again. The shader_ ones still seem broken because they use #define. These functions really need to be refactored to be consistent but this at least gives users some way to use shaders for now.

include shader funcs still a mess tho

---

CI/build_and_run_game.sh
azure-pipelines.yml

Disable mono/gecko install prompts causing job to hang. Apparently we need to start pulse too

Wine CI fix

---

CI/solve_engine_deps.sh
ENIGMAsystem/SHELL/Widget_Systems/xlib/Info/About.ey
ENIGMAsystem/SHELL/Widget_Systems/xlib/Makefile
ENIGMAsystem/SHELL/Widget_Systems/xlib/dialogs.cpp
ENIGMAsystem/SHELL/Widget_Systems/xlib/dialogs.h
ENIGMAsystem/SHELL/Widget_Systems/xlib/zenity.cpp

tl;dr. In the process of me trying to fix dialogs, I accidentally broke them in a different way, while not actually fixing anything. 
https://github.com/enigma-dev/enigma-dev/commit/a019ab6c06cd922d264abef7f0f3a154d66c867d
When ci passes please merge. Posix threads are a more technically correct approach than using a fork anyway.
On Unix likes, regardless of the default shell executable that's actually being used, getting the first argument in the command line will return "/bin/sh" and this has been confirmed from testing. The problem was I wasnt getting a pid match with the launched process and kdialog/zenity because it was giving me the process id of the default shell instead; this code filters out the default shell to ensure a pid match so we can verify the topmost window is owned by …

umm, i can explain

---

ENIGMAsystem/SHELL/Universal_System/bufferstruct.cpp

It works!!!!!
Allows my video player in https://github.com/enigma-dev/enigma-dev/pull/2214 to render pixels to a surface from buffer_get_address().
Screenshot taken on FreeBSD. Note FreeBSD is the only platoform my other pr (the video player one) currently works in, on Windows and Linux you will get undefined references, which I am in the process of figuring out before that pr will be ready for merging. 
However this is a separate task entirely, and should be good to go when the CI passes.

Implement buffer_set_surface().

---

ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp

Following Aj's #2230 pull, I am removing this old dead code from the Win32 platform. The history of this code starts with @polygoned when he originally attempted to add the scaling options (9c1dd6b891caf4a1594f47aaa708893afd4644fd) to ENIGMA. He made the EXIT/end resize event be the one to redo the scaling calculation. Since that time we've cleaned that code up and abstracted it to apply to all platforms. However, we left a lot of his dead manual code in here that isn't needed anymore. This removes it, with no change in behavior as far as I can tell from my testing. We still compute scale in the normal resize event.

Cleanup Win32 Resize Scaling

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSd3d.cpp

I started working on this because of #2237 where I can't get a 3D SOG game to run because of an assertion in GLM perspective. The reason was because SOG games don't have views initialized and GLM is asserting on `d3d_start` passing 0 for aspect ratio. Luckily for me, `d3d_start` is actually incorrect with respect to intended behavior.
In GameMaker, switching to 3D mode automatically switches to perspective projection. However, this means perspective mode, which controls the default camera of the draw loop, not a one time projection. This is why it is unnecessary for us to set a projection immediately when start and end are called. I actually fixed perspective mode in #1388. There is no need to turn perspective off since in that same pull request I check in the draw loop if 3D mode and …

Fix D3D Mode Projection

---

appveyor.yml

They killed off pacboy, which I had used to save the world a few characters. That change has finally propagated to AppVeyor's CI systems, and now I need to update it there. Actually, they didn't remove it, just stopped including pactoys in base install. Let's just get it out of our CI for good since it only complicates things.
```
msys/pactoys-git r2.07ca37f-2
A set of pacman packaging utilities
```

Remove AppVeyor Pacboy

---

ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
ENIGMAsystem/SHELL/Platforms/General/PFmain.h
ENIGMAsystem/SHELL/Platforms/General/POSIX/Utility.cpp
ENIGMAsystem/SHELL/Platforms/None/fillin.cpp
ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp
ENIGMAsystem/SHELL/Platforms/platforms_mandatory.h
ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp

I generalized the timing code using high precision `std::chrono` in place of the performance counters. I was originally going to use [SDL_GetPerformanceCounter](https://wiki.libsdl.org/SDL_GetPerformanceCounter) and [SDL_GetPerformanceFrequency](https://wiki.libsdl.org/SDL_GetPerformanceFrequency) to generalize only the timers themselves. However, C++11 has been around long enough that I don't need to and fundies said Android even probably supports chrono at this point.
I have no idea if any of @forthevin's original logic can be further simplified. I do know there are comments left in here directed at @JoshDreamland about Win32 and Xlib's relative order of updating the timer and processing events. I did have to add a 4th timer start variable, due to the nature of chrono being wall-clock …

Use std::chrono for Main Loop Timing

---

ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSbasic.cpp

This is a recreation of #2166 because my branches got overloaded. The code is all correct but will not work yet as `DSBCAPS_CTRLFX` cannot be added to the buffers until #1508 is figured out for short audio clips.
* Fix memory leak on reference-counted COM interfaces by using ComPtr
* Fix memory leak in `sound_effect_set` by using stack-allocated vector for effect description arrays
* Implement all sound effect parameter functions using a generic templated helper
```gml
// create event
effect = se_none;
// step event
if (keyboard_check_released(ord('0')))
effect = se_none;
if (keyboard_check_released(ord('1')))
effect ^= se_chorus;
if (keyboard_check_released(ord('2')))
effect ^= se_echo;
if (keyboard_check_released(ord('3')))
effect ^= se_flanger;
if (keyboard_check_released(ord('4'))) …
```

DirectSound Environmental Audio

---

ENIGMAsystem/SHELL/Graphics_Systems/General/GSscreen.cpp
ENIGMAsystem/SHELL/Graphics_Systems/General/GSsurface.cpp
ENIGMAsystem/SHELL/Universal_System/Resources/backgrounds.cpp
ENIGMAsystem/SHELL/Universal_System/Resources/sprites.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.cpp
ENIGMAsystem/SHELL/Universal_System/image_formats.h

Fixes #353 using nearest neighbors to remove the target color from the image. This is close to what GameMaker itself does in that it's not destructive to the color channels, only the alpha channels. It addresses an issue introduced by #1937 whereby the color channel is not replaced by black now which further worsened texture interpolation.
| Master | Pull |
|--------|------|
|![Master Image Color Swap](https://user-images.githubusercontent.com/3212801/141053390-b3213512-5852-46ca-a024-e4993601ced0.png)|![Pull Request Nearest Neighbor Image Color Removal](https://user-images.githubusercontent.com/3212801/141234680-94371ec2-da10-4c8c-aa8e-47162d3f168d.png)|
This also fixes another issue with sprite transparency where we're only using the bottom-left pixel of the first frame for the entire …

Nearest Neighbor Color Removal

---

ENIGMAsystem/SHELL/Platforms/None/fillin.cpp

Some of the POSIX headers don't even exist on Windows and they weren't even being used in there anyway. This fixes #2219 specifically but does not fully fix the issue of building the None Platform on Windows as for some reason somebody also linked POSIX in the None system makefile.

Cleanup None Platform Includes

---

ENIGMAsystem/SHELL/Universal_System/image_formats.cpp

Hi, this is the fix which updates the bmp header present in `image_save_bmp(...)` method of `image_formats.cpp` from 40 byte `BITMAPINFOHEADER` to 108 byte `BITMAPV4HEADER` to support transparency.
Reference used for fix: [BMP_Wiki](https://en.wikipedia.org/wiki/BMP_file_format).

BMP write bug fix #2101

---

CommandLine/testing/Platform/TestHarness-X11.cpp

`build_game` returns with the following codes:
- `0` if `execvp` successfully launches `emake`.
- A value `>0` if `emake` launches but exits with non zero return code.
- `-1` if `execvp` fails to launch `emake`.
These return codes are checked by `launch_and_attach` and `run_to_completion` here:
```
if (int retcode = build_game(game, tc, out)) {
if (retcode != -1) {
std::cerr << "Failed to run emake." << std::endl;
} else {
std::cerr << "emake returned " << retcode << "; abort" << std::endl;
}
return nullptr;
}
```
When `build_game` fails to launch `emake` then `retcode` holds `-1` which gets compared with `-1`  using `!=` evaluating to `false` hence `Failed to run emake` never gets into cerr. Replacing `!=` with `==` ensures correct behavior.

Fix checking return code of build_game function in testharness

---

CommandLine/libEGM/egm-read.cpp

This is a small fix for the issue in which on loading egm projects in RGM, folders appears in place of actual resources.
The issue is a side effect of calling `mutable_folder` before checking if node contains `folder` or not, as a call to `mutable_folder` creates an unwanted `folder` which was happening in `void RecursiveResourceSanityCheck(...)` of `egm-read.cpp`.

Fix 'folder replaces resource' egm-read issue

---

CompilerSource/compiler/jdi_utility.cpp
CompilerSource/gcc_interface/gcc_backend.cpp
CompilerSource/languages/lang_CPP.cpp
CompilerSource/languages/language_adapter.cpp
CompilerSource/main.cpp
CompilerSource/parser/parser_components.cpp

This fixes the build errors which showed up when running `make all`
NOTE: The changes in `jdi_utility.cpp` should be reviewed, as they are just a hack to get the build to finish

Fix more build errors with JDI update

---

CommandLine/emake-tests/Parsing/lexer-test.cpp
CompilerSource/parsing/lexer.cpp
CompilerSource/parsing/lexer.h
CompilerSource/parsing/macros.cpp
CompilerSource/parsing/macros.h

These series of commits:
1. Adds a test to check macro expansion
2. Fixes the closing parenthesis of macros being considered as a macro argument
3. Fixes incorrect strings being used when stringifying a macro argument

WIP: Fixes for macros in EDL lexer

---

CommandLine/emake/OptionsParser.cpp
CompilerSource/compiler/compile.cpp
CompilerSource/settings-parse/parse_ide_settings.cpp
CompilerSource/settings.h

add a `-j` flag to emake for that yoinky sploinky

emake: add -j flags to specify compile jobs

---

CommandLine/emake/Main.cpp

Fixes issue #2296
Fixed the issue by making a condition checking if the file name is not empty and that it doesn't exist.

emake doesn't show error finding input file bug fix

---

CommandLine/libEGM/serialization-helpers.h

When running ``make emake`` on windows it gives an error:
<https://gist.github.com/k0T0z/82a0454fd99070d54143492d5d0e10ae>
this PR contains a fix for this error.

fix for emake build error on windows

---

ENIGMAsystem/SHELL/Universal_System/actions.h

Added all the event constants for the newer async events, which can later be used to implement `event_perform_async`

Async Event Constants

---

ENIGMAsystem/SHELL/Universal_System/Instances/instance.h
ENIGMAsystem/SHELL/Universal_System/Instances/instance_create.h

Also fixed `instance_copy` so that it inits the copied variables before calling the create event.

add instance_create_depth

---

ENIGMAsystem/SHELL/Universal_System/Extensions/Steamworks/README.md
ENIGMAsystem/SHELL/Universal_System/Extensions/Steamworks/gameclient/utils/gc_leaderboards_score_downloaded_cookies.cpp

Fixes #2370.
Previously the userId of the steam users was shown as it is in integer form.
Since this is not desirable, this PR converts the integer into a **hexadecimal number** , prepends it with `@i64@` and appends it with `$i64$` before getting output on the leaderboard.
changed lines 53/54 in the [file](https://github.com/enigma-dev/enigma-dev/blob/3918af3dc40734465b355a7d52cb9f9f93f5a8d6/ENIGMAsystem/SHELL/Universal_System/Extensions/Steamworks/gameclient/utils/gc_leaderboards_score_downloaded_cookies.cpp#L53) to handle hex conversion.

Steamworks : UserId from UInt64 to Hex

---

CommandLine/emake/Makefile

Fixes the following error building emake on Linux...
> /usr/bin/ld: cannot find -labsl_log_internal_message: No such file or directory
/usr/bin/ld: cannot find -labsl_log_internal_check_op: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [../../Default.mk:23: ../../emake] Error 1
make[1]: Leaving directory '/home/ubuntu/enigma-dev/CommandLine/emake'
make: *** [Makefile:51: emake] Error 2
...and just like that, it builds again!

Fix Building emake on Linux
