- CompilerSource/compiler/components/write_room_data.cpp
- ENIGMAsystem/SHELL/Universal_System/roomsystem.h
Fixes https://github.com/enigma-dev/enigma-dev/pull/925 with Josh's approach.
> All creation/pre-creation code (rooms and instances) returns variants (default 0).

- .travis.yml
- travishelper.sh
This uses a hacky sudo method with a bash script to set up travis with c++11.
> add Travis CI (travishelper.sh)

- ENIGMAsystem/SHELL/Universal_System/mathnc.h
As mentioned by @JoshDreamland in #959
> Added overload for const var& in int64()

- ENIGMAsystem/SHELL/Universal_System/instance.cpp
Request created in GitHub. Someone please verify this builds and runs, since I still haven't set up a build bot.
This request should fix #976.
> Fix instance_number to handle collection constants

- CompilerSource/gcc_interface/gcc_backend.cpp
- ENIGMAsystem/SHELL/Mock_JDI_Headers/string
This should fix #1102 and #1055.
> Add mock string header to JDI include path.

- ENIGMAsystem/SHELL/Universal_System/instance_system.cpp
- ENIGMAsystem/SHELL/Universal_System/instance_system_base.h
This fixes enemies getting stuck in corners in Daniel Remar's Violet Metal, however I'm 99.9% sure this is the wrong fix.
Explanation:
In the `scr_sabotcreate` script (in Violet Metal), which runs at the start of each level, there's this code:
```c
//Place start blocks
with (obj_block)
instance_create(x,y,obj_startblock);
//Calculate crossings
for (i=0;i<320;i+=16){
for (j=0;j<240;j+=16){
if (place_free(i,j)){
......
```
The script (`scr_sabotcreate`) runs on the "Create" event of `obj_sabot`, of which there is one per room, thus making it the script that runs when entering a new room (level). So, the object the script runs "on" is the `obj_sabot` instance.
Now, the problem:
When exiting the `with (obj_block)`, the "current object" - instead of being restored to the initial `obj_sabot` …
> [WIP/hack] Restore previous instance when exiting with

- CommandLine/emake/EnigmaPlugin.cpp
- CommandLine/emake/EnigmaPlugin.hpp
- CommandLine/emake/Main.cpp
- CommandLine/emake/OptionsParser.cpp
- CommandLine/emake/OptionsParser.hpp
- CompilerSource/compiler/compile.cpp
- CompilerSource/compiler/components/write_defragged_events.cpp
- CompilerSource/compiler/components/write_font_info.cpp
- CompilerSource/compiler/components/write_globals.cpp
- CompilerSource/compiler/components/write_object_access.cpp
- CompilerSource/compiler/components/write_object_data.cpp
- CompilerSource/compiler/components/write_room_data.cpp
- CompilerSource/compiler/components/write_shader_data.cpp
- CompilerSource/gcc_interface/gcc_backend.cpp
- CompilerSource/languages/lang_CPP.cpp
- CompilerSource/main.cpp
- CompilerSource/makedir.cpp
- CompilerSource/makedir.h
- CompilerSource/settings-parse/parse_ide_settings.cpp
- ENIGMAsystem/SHELL/Makefile
- Makefile
- settings.ey
close  #805 when this is merged
> refactor makedir/codegen

- CompilerSource/compiler/components/module_write_fonts.cpp
- CompilerSource/compiler/reshandlers/rectpack.cpp
- CompilerSource/compiler/reshandlers/rectpack.h
- ENIGMAsystem/SHELL/Graphics_Systems/General/GSfont.cpp
- ENIGMAsystem/SHELL/Universal_System/fontinit.cpp
- ENIGMAsystem/SHELL/Universal_System/fonts_internal.h
- ENIGMAsystem/SHELL/Universal_System/fontstruct.cpp
- ENIGMAsystem/SHELL/Universal_System/make_unique.h
- ENIGMAsystem/SHELL/Universal_System/mathnc.cpp
- ENIGMAsystem/SHELL/Universal_System/mathnc.h
- ENIGMAsystem/SHELL/Universal_System/rectpack.cpp
- ENIGMAsystem/SHELL/Universal_System/rectpack.h
- ENIGMAsystem/SHELL/Universal_System/texture_atlas.cpp
rect_packer is still duplicated. I'm not sure who should own it. Perhaps we need a a shared folder. Eitherway, atleast one makefile will need modification to remove one of the copies
> fixes some mem leaks related to font crap I'm working on

- CommandLine/testing/SimpleTests/math_test.sog/create.edl
- CommandLine/testing/SmallTests.cpp
- CompilerSource/JDI/src/System/builtins.cpp
- CompilerSource/compiler/jdi_utility.cpp
- CompilerSource/compiler/jdi_utility.h
- CompilerSource/frontend.cpp
- CompilerSource/standalone_main.cpp
- CompilerSource/syntax/syntax.cpp
- ENIGMAsystem/SHELL/Universal_System/Extensions/GTest/GTest.cpp
- ENIGMAsystem/SHELL/Universal_System/Extensions/GTest/include.h
- ENIGMAsystem/SHELL/Universal_System/dynamic_args.h
- ENIGMAsystem/SHELL/Universal_System/generic_args.h
- ENIGMAsystem/SHELL/Universal_System/mathnc.cpp
- ENIGMAsystem/SHELL/Universal_System/mathnc.h
- ENIGMAsystem/SHELL/Universal_System/scalar.h
- ENIGMAsystem/SHELL/libEGMstd.cpp
- ENIGMAsystem/SHELL/libEGMstd.h
- Makefile
See individual commits for more details. I will rebase them into master.
Note that the first four commits are already merged.
> Rewrite mathnc and GTest, improve jdi_util and IDE frontend to it.

- .travis.yml
- Compilers/Linux/TestHarness.ey
- ENIGMAsystem/SHELL/Universal_System/Extensions/Paths/pathinit.cpp
- ENIGMAsystem/SHELL/Universal_System/backgroundinit.cpp
- ENIGMAsystem/SHELL/Universal_System/fontinit.cpp
- ENIGMAsystem/SHELL/Universal_System/image_formats.cpp
- ENIGMAsystem/SHELL/Universal_System/soundinit.cpp
- ENIGMAsystem/SHELL/Universal_System/spriteinit.cpp
enables undefined behavior runtime checks in test harness and fixes some undefined behavior in game startup
> Robert is an idiot

- .travis.yml
Fucking thing's pretty annoying. Half the scrollback is join/parts.
> Make the travis bot stay in ENIGMA's IRC

- ENIGMAsystem/SHELL/Platforms/General/PFmain.h
- ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp
- ENIGMAsystem/SHELL/Platforms/General/PFwindow.h
- ENIGMAsystem/SHELL/Platforms/None/fillin.cpp
- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp
- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
- ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp
> remove duplicate windows functions

- CommandLine/emake/OptionsParser.cpp
- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp
Fixing the issues I raised in #1261 stemming from #1259 and #1248
> Assfroto fixes

- ENIGMAsystem/SHELL/Widget_Systems/TinyFileDialogs/dialogs.cpp
to match how GMS works with its directory functions and constants i.e. working_directory
> get_directory/_alt now return dir with final slash

- CommandLine/testing/GitHub-ImageDiff.sh
- ENIGMAsystem/SHELL/Graphics_Systems/General/GSstdraw.cpp
> OAuth for EnigmaBot Commenting

- CommandLine/emake/Proto2ES.cpp
This is very simple, I am just getting a start on the conversion of the new Settings proto to the old EnigmaStruct game settings. I'll be following this pr up with additional changes as I continue to work on these facilities. This doesn't change it to actually use the method yet, just provides an implementation of the method with the basic settings that exist now.
> Settings Proto Conversion to EnigmaStruct

- CommandLine/libEGM/gmk.cpp
- CommandLine/protos/Settings.proto
This is pretty simple too, just read the settings from the GMK into the new Settings proto format.
> Read GMK Settings in libEGM

- appveyor.yml
We weren't testing OpenAL in AppVeyor because it wasn't working in run or compile mode. It now at least works in run mode, so we should add a test job for it.
> AppVeyor/OpenAL Job

- ENIGMAsystem/SHELL/Platforms/SDL/Joystick.cpp
my last pr broke all joystick shit. this goes against my religion. better get fixed right quick.
> this should unfuck the fucked up Joystick pr

- ENIGMAsystem/SHELL/Widget_Systems/DlgMod/dialogs.cpp
- ENIGMAsystem/SHELL/Widget_Systems/DlgMod/dialogs.h
- ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.cpp
- ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.h
- shared/tinyfiledialogs/tinyfiledialogs.cpp
Add the following functions to all my Widget Systems:
- get_open_filenames(filter, fname)
- get_open_filenames_ext(filter, fname, dir, title)
- get_color_ext(defcol, title)
> Add Support for Multi-Select Open File Dialogs

- ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.cpp
- shared/tinyfiledialogs/tinyfiledialogs.cpp
previously the inconsistent indentation used in TFD was one big mess and made it a tiny bit difficult to read and looked very sloppy. This should fix it for the most part, if not completely.
I kinda wanted to go even further and make this file match the rest of ENIGMA's intended indentation and syntax practices, but I was too afraid I'd accidentally mess up the file somewhere. Maybe some day...
I also promised Josh I would add a helper function in a different file so I did that as well.
> Made TFD easier to read

- ENIGMAsystem/SHELL/Widget_Systems/General/tinyfiledialogs/dialogs.cpp
This fixes a mac compile error when using OsaScript.
> Forgot extern "C"

- ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/Info/About.ey
I want to provide a more meaningful description for the OpenGL1 system that reflects the reasons we created and maintain it. A good reason for doing this is so that user's have a better understanding of the when, where, why, and how the system should be applied and used.
> Update OpenGL1 System Description

- ENIGMAsystem/SHELL/Audio_Systems/OpenAL/Info/About.ey
I think it's a good idea for us to update the system description for OpenAL. We need to give the user an idea of what this system provides and why to select it.
> Update OpenAL System Description

- ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.cpp
This fixes everything that was broken in Cocoa Widgets. Not much needed to be changed/fixed.
> Fix Cocoa Widgets Errors

- ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.cpp
sorry, I missed something. I forgot to make show_error abort the application when necessary.
> fix last bug with Cocoa Widgets

- CommandLine/testing/SimpleTests/data_structure_test.sog/create.edl
- CommandLine/testing/SmallTests.cpp
- ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp
I want to get #1649 fixed in master for Darkstar2. I am creating this pull request with a continuous integration test to first validate that master is not correct with respect to the GM behavior. This test will eventually cover all data structures, but for now, I've only done the lists. Then I will commit the fix for sorting strings.
> List Sorting & Data Structures CI Test

- ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.cpp
I have been informed that this is how it goes around here
> Change tabs in GSsprite.cpp to be two spaces

- ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.cpp
As requested; you can evidently go further than this, but this is already much better than having similar primitive construction in pretty much every function
> Unify draw_sprite_* implementations a little

- ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9d3d.cpp
- ENIGMAsystem/SHELL/Graphics_Systems/General/GSd3d.cpp
- ENIGMAsystem/SHELL/Graphics_Systems/General/GSd3d.h
- ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLd3d.cpp
- ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3d3d.cpp
This is a friend of #1687 which is in the same boat. I accidentally caused a regression to the ambient lighting color in #1636.
> Fix Ambient Lighting Color

- CommandLine/testing/SimpleTests/data_structure_test.sog/create.edl
This pull request is a friend of #1697 where I am expanding the same data structures CI test to cover stacks.
> Add DS Stack Tests To CI

- CommandLine/testing/SimpleTests/data_structure_test.sog/create.edl
This pull request is a friend of #1698 and #1697 which expands coverage to include data structure queues.
> Add DS Queue Tests To CI

- ENIGMAsystem/SHELL/Graphics_Systems/General/GSmodel.cpp
flips texture on cylinder to be right-side up
> Fix 3D Cylinder Side Texturing

- ENIGMAsystem/SHELL/Widget_Systems/Win32/Info/About.ey
- ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
Tested locally this time. Fixes https://github.com/enigma-dev/enigma-dev/issues/1768
Demo GMK and x86 EXE: [Win32.zip](https://github.com/enigma-dev/enigma-dev/files/3347667/Win32.zip)
> Fix file dialog bug previously merged

- CommandLine/libEGM/gmk.cpp
I am bringing this fix over from LateralGM.
https://github.com/IsmAvatar/LateralGM/commit/9d83c566301ff1b52d8f151b1892f89e06707af6
> GM81 libegm Clear View Fix

- ENIGMAsystem/SHELL/Graphics_Systems/Direct3D11/DX11vertex.cpp
- ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9vertex.cpp
- ENIGMAsystem/SHELL/Graphics_Systems/OpenGL-Common/vertex.cpp
- ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/vertex.cpp
I am making this change by itself so it's clear what's going on before I do other fixes in here. All I am doing is checking if not dirty and returning. Before we were checking if dirty and indenting the code and sometimes having an else statement.
There is absolutely no change to the logic here, and I tested hard to make sure.
> Vertex Prepare Dirty Exit

- ENIGMAsystem/SHELL/Platforms/General/PFmain.cpp
- ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp
- ENIGMAsystem/SHELL/Universal_System/Resources/loading.cpp
- ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp
Originally I was firing window_center() for 15 steps in a row, to accommodate for the fact, it would not center regardless sometimes. This time, I changed it so that it while loops until it is centered.
> better approach for game init

- ENIGMAsystem/SHELL/Widget_Systems/Win32/dialogs.cpp
- ENIGMAsystem/SHELL/Widget_Systems/xlib/Info/About.ey
- ENIGMAsystem/SHELL/Widget_Systems/xlib/dialogs.cpp
- ENIGMAsystem/SHELL/Widget_Systems/xlib/kdialog.cpp
- ENIGMAsystem/SHELL/Widget_Systems/xlib/zenity.cpp
yes, *another* widget tweak...
> Small Tweak

- ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.m
pleasure mudge. this has already been well tested and well fucked with lots and lots of man love.
> [macOS Catalina compatible] remove deprecated shit

- CommandLine/testing/SimpleTests/object_inheritance.gmx/object_inheritance.project.gmx
- CommandLine/testing/SimpleTests/object_inheritance.gmx/objects/obj_controller.object.gmx
- CommandLine/testing/SimpleTests/object_inheritance.gmx/objects/obj_grandchild.object.gmx
- CommandLine/testing/SimpleTests/object_inheritance.gmx/objects/obj_grandchild_grandparent.object.gmx
- CommandLine/testing/SimpleTests/object_inheritance.gmx/objects/obj_grandchild_parent.object.gmx
- CommandLine/testing/SimpleTests/object_inheritance.gmx/objects/obj_single.object.gmx
- CommandLine/testing/SimpleTests/object_inheritance.gmx/objects/obj_single_parent.object.gmx
- CommandLine/testing/SimpleTests/object_inheritance.gmx/rooms/rm_0.room.gmx
Just testing out the basics of inheritance which is everything I ever expected to work in the existing implementation. I test variable inheritance and event overriding. I also test a single inheritance as well as a grandparent inheritance relationship.
> Object Inheritance Test

- CommandLine/libEGM/CMakeLists.txt
- shared/protos/CMakeLists.txt
@RobertBColton can you merge this for me pls
> fixes for cpack

- shared/protos/CMakeLists.txt
partner of https://github.com/enigma-dev/RadialGM/pull/101
> actually disable grpc when no grpc & fix grpc hang on linux

- ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp
The previous method made the window change position to weird places on some lesser used WM's such as Budgie. This implementation should be less WM-dependent and a more universally correct approach.
> [X11] More Reliable window_set_showborder() Function

- ENIGMAsystem/SHELL/Universal_System/Extensions/FileDropper/FileDropper.cpp
[FileDropper.zip](https://github.com/enigma-dev/enigma-dev/files/4398237/FileDropper.zip)
> Allow Drag and Drop when Running Program as Admin

- ENIGMAsystem/SHELL/Universal_System/Extensions/FileDropper/FileDropper.cpp
fuck joo for merging a pr that didn't pass ci
> @JoshDreamland fuck joo bitch

- CommandLine/libEGM/gmx.cpp
- shared/protos/Path.proto
> fix gmx path background room

- CI/dump_codegen.sh
- CommandLine/emake/OptionsParser.cpp
- CompilerSource/compiler/compile.cpp
- CompilerSource/settings-parse/parse_ide_settings.cpp
- CompilerSource/settings.h
- Makefile
must be merged before #2014 to keep ci happy
> appease ci gods

- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
this change fixes a weird problem with fullscreen that's hard to explain visually and I'm too lazy to take screenshots.
> Fix Windows Fullscreen

- ENIGMAsystem/SHELL/Platforms/Android/AndroidWindow.h
- ENIGMAsystem/SHELL/Platforms/Cocoa/CocoaMain.h
- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.h
- ENIGMAsystem/SHELL/Platforms/iPhone/CocoaWindow.h
I have no idea what this was for, but it doesn't seem to be used anymore.
> Cleanup Vestigial Catch Mouse

- ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp
- ENIGMAsystem/SHELL/Platforms/None/fillin.cpp
- ENIGMAsystem/SHELL/Platforms/SDL/Window.cpp
- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp
- ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp
This was duplicated all over with the same logic.
> Cleanup I/O Handling

- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSshell.cpp
- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSthreads.cpp
Let's continue from #2043 and clean up the rest of the rest of the duplicate message pumps.
> Win32 Cleanup Message Pumps

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
This should send all the RGM/LGM/plugin bug reports off to the right locations.
> Issue Template Configuration & Feature Request Template

- ENIGMAsystem/SHELL/Platforms/General/include.h
> Cleanup General Platform Include

- ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSicon.cpp
> fcuk adn garb icn leke right by the pussy !!!!

- azure-pipelines.yml
> arch moved packages

- ENIGMAsystem/SHELL/Universal_System/Extensions/FileDropper/FileDropper.cpp
robert, robert, why oh why did you roam? come home, come home!
https://peanuts.fandom.com/wiki/Snoopy,_Come_Home_(song)
> bumble bee tuna

- appveyor.yml
Appveyor currently takes 8hrs to complete and goober convinced josh to make it blocking. I've combined most the jobs to save some time.
> Combine appveyor jobs

- ENIGMAsystem/SHELL/Universal_System/Extensions/libpng/libpng-util.cpp
Simplify libpng include. This was causing error in directx11 for some reason I cba to trace
> Fix include

- appveyor.yml
MSys team added a keyboard prompt and terminal reset, which is breaking the CI.
> Skip MSys update in AppVeyor

- CommandLine/emake-tests/Parsing/lexer-test.cpp
- CompilerSource/compiler/components/parse_and_link.cpp
- CompilerSource/compiler/components/write_object_data.cpp
- CompilerSource/compiler/components/write_room_data.cpp
- CompilerSource/parser/collect_variables.cpp
- CompilerSource/parser/object_storage.h
- CompilerSource/parser/parser.cpp
- CompilerSource/parser/parser_components.cpp
- CompilerSource/parsing/ast.cpp
- CompilerSource/parsing/ast.h
- CompilerSource/parsing/language_frontend.h
- CompilerSource/parsing/lexer.cpp
- CompilerSource/parsing/macros.cpp
Need to figure out how to deal with move semantics in AST / Lexer.
> I'm stuck on move semantics

- ENIGMAsystem/SHELL/Audio_Systems/DirectSound/DSbasic.cpp
- ENIGMAsystem/SHELL/Audio_Systems/General/ASbasic.h
- ENIGMAsystem/SHELL/Audio_Systems/OpenAL/ALbasic.cpp
- ENIGMAsystem/SHELL/Audio_Systems/SDL/Info/About.ey
- ENIGMAsystem/SHELL/Audio_Systems/SDL/Info/audio_info.h
- ENIGMAsystem/SHELL/Audio_Systems/SDL/Makefile
- ENIGMAsystem/SHELL/Audio_Systems/SDL/SDLadvanced.cpp
- ENIGMAsystem/SHELL/Audio_Systems/SDL/SDLbasic.cpp
- ENIGMAsystem/SHELL/Audio_Systems/SDL/SDLsystem.cpp
- ENIGMAsystem/SHELL/Audio_Systems/SDL/SDLsystem.h
- ENIGMAsystem/SHELL/Audio_Systems/SDL/SoundChannel.h
- ENIGMAsystem/SHELL/Audio_Systems/SDL/SoundResource.h
- ENIGMAsystem/SHELL/Audio_Systems/SDL/include.h
- ENIGMAsystem/SHELL/Platforms/General/include.h
- ENIGMAsystem/SHELL/Platforms/SDL/Android/android.cpp
- ENIGMAsystem/SHELL/Platforms/SDL/Makefile
> Addition of SDL audio_system

- ENIGMAsystem/SHELL/Makefiles/MacOSX/Android/Makefile
- ENIGMAsystem/SHELL/Makefiles/MacOSX/AndroidSym/Makefile
- ENIGMAsystem/SHELL/Makefiles/MacOSX/iPhone/Makefile
- ENIGMAsystem/SHELL/Makefiles/MacOSX/iPhoneSim/Makefile
> Delete ENIGMAsystem/SHELL/Makefiles/MacOSX directory

- .vscode/settings.json
- ENIGMAsystem/SHELL/Graphics_Systems/General/GStextures.h
Another build failed due to missing the same include
https://gist.github.com/k0T0z/82a0454fd99070d54143492d5d0e10ae
> Fix grphics sys build failed

- ENIGMAsystem/SHELL/Universal_System/Extensions/Json/json.cpp
- ENIGMAsystem/SHELL/Universal_System/Extensions/Json/json_value.cpp
@RobertBColton I found out that to fix #2339, I have to specify the starting point if it's a list or a map and that's it. I provided a fix for it in #2335, but it's wrong i guess.
> fix #2339 the right way

- CommandLine/emake-tests/Parsing/parser-test.cpp
- CompilerSource/parsing/parser.cpp
In this PR, I added new tests and 2 new functions `ParseStatementOrBlock` and `TryParseDeclOrTypeExpression`.
> `ParseStatementOrBlock` and `TryParseDeclOrTypeExpression`

- .gitignore
- CommandLine/emake/CMakeLists.txt
- CommandLine/emake/Makefile
- CommandLine/libEGM/CMakeLists.txt
- CompilerSource/CMakeLists.txt
- Config.mk
- Makefile
- shared/CMakeLists.txt
- shared/protos/CMakeLists.txt
- shared/protos/Makefile
This PR contains the full build fixes. It must be merged with https://github.com/enigma-dev/RadialGM/pull/240.
The work is extracted from my other work #2399.
@RobertBColton
> Fix building issues
